### ISSUE TITLE
why `await`? 

### ISSUE THREAD

**Issue by SidKwok** [thomasdondorf/puppeteer-cluster#10]
Cool project, but I am confused that why you use `await` in your example:

```javascript
const { Cluster } = require('puppeteer-cluster');

(async () => {
  const cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_CONTEXT,
    maxConcurrency: 2,
  });
  
  // Is `await` necessary?
  await cluster.task(async ({ page, data: url }) => {
    await page.goto(url);
    const screen = await page.screenshot();
    // Store screenshot, do something else
  });

  await cluster.queue('http://www.google.com/');
  await cluster.queue('http://www.wikipedia.org/');
  // many more pages

  await cluster.idle();
  await cluster.close();
})();
```

when you define a `task` or try to add some queues, why `await`? I try to remove them and is ok to do that.

**Comment by SidKwok** [comment]
> Right now the functions task and queue have only synchronous calls inside.

You mean `cluster.queue('http://www.wikipedia.org/')` will be called after `cluster.queue('http://www.google.com/')` finish?

**Comment by thomasdondorf** [comment]
No, I meant there are no await (asynchronous) calls inside of the task and queue functions. The functions are very simple and don't need to be `async` right now.

**Comment by SidKwok** [comment]
I got it. The doc indicate that all functions `on cluster.*` return Promises. The example may cause confusion that `cluster.queue('http://www.wikipedia.org/')` will be called after `cluster.queue('http://www.google.com/')` finish, take `axios` as example:
```javascript
await axios.get('http://api.org/get-name');
// will be called after the above function is finished
await axios.get('http://api.org/get-age');

// both will be called asynchronously
axios.get('http://api.org/get-name');
axios.get('http://api.org/get-age');
```

Hope it only causes confusion for me lol.

**Comment by thomasdondorf** [comment]
Thank you. I had not thought about it that way. Maybe the `await` should be removed then?

I have to think about this. Feedback is welcome :)

**Comment by thomasdondorf** [comment]
`await` really seems to confuse people: https://stackoverflow.com/questions/46597304/how-to-enable-parallel-tests-with-puppeteer/51408815#comment92960172_51408815

Currently I'm in favor of removing `await` from the documentation, but keeping the returning of a Promise to not break compatibility with previous versions.

**Comment by SidKwok** [comment]
I think people would use `queue` to define a task and add it to end of the queue. Is it really necessary to return a Promise in this case?

**Comment by thomasdondorf** [comment]
I implemented the `execute` function which hopefully makes things clearer. Right now I think there are three options on how to proceed:

1. Remove Promise from `queue` function and return `void` instead of `Promise<void>`
2. Still return a Promise, but remove all `await cluster.queue(..)` from documentation
3. Continue as is.

I prefer option 2 as this keeps backward compatibility and will most likely remove the `await`s from documentation.

**Comment by SidKwok** [comment]
Option 2 seems nice.

**Comment by thomasdondorf** [comment]
I removed the `await`s from all `cluster.queue` examples and added this hint to the docs: 

"Be aware that this function only returns a Promise for backward compatibility reasons. This function does not run asynchronously and will immediately return."

I guess that should clear any confusion in the future.
