### ISSUE TITLE
Export interfaces

### ISSUE THREAD

**Issue by fforres** [thomasdondorf/puppeteer-cluster#101]
First of all, awesome library! :) @thomasdondorf 

Wanted to ask one thing, I'm currently building a project based on puppeteer-cluster and TS and wanted to properly define types for our public interface.

For that, I wanted to check if you'd be OK with exposing the internal interfaces on the codebase.

https://github.com/thomasdondorf/puppeteer-cluster/blob/22658e22dd1c08537dcb90038ea53fe3e9c44821/src/Cluster.ts#L18
https://github.com/thomasdondorf/puppeteer-cluster/blob/22658e22dd1c08537dcb90038ea53fe3e9c44821/src/Cluster.ts#L54
https://github.com/thomasdondorf/puppeteer-cluster/blob/22658e22dd1c08537dcb90038ea53fe3e9c44821/src/Cluster.ts#L36

I would love adding a PR for it, wanted to check on you first

**Comment by thomasdondorf** [comment]
Thanks. Sound good, feel free to submit a PR :)
Just make sure to comment on the PR to confirm you are okay with a license change in the future. (see #81)

**Comment by fforres** [comment]
MIT is a great choice, I'm ok with it :) 
WIll add it once I create the PR as well
