### ISSUE TITLE
Taskerror page instance

### ISSUE THREAD

**Issue by mtatarau90** [thomasdondorf/puppeteer-cluster#106]
Hi, 
I think is a good idea to an instance of "page" tot taskerror event. I saw that if i have timeout the error fires taskerror event, but i don't have page instance to close the tab. 

What do you think guys?

**Comment by thomasdondorf** [comment]
Hi :)

You want to provide the page object to the "taskerror" handler? I don't think that is a good idea, as the page might have crashed or even the browser, so calling any function on it might just lead to another error.

And you don't need to close the page. This will be done for you, even in case of an error.

**Comment by mtatarau90** [comment]
Perhaps you are right, is not a good idea, but we need a way to close a browser tab when the sluster gave us a taskerror. 

You have any ideea how we can do that?

**Comment by thomasdondorf** [comment]
The cluster will [always try to close the page](https://github.com/thomasdondorf/puppeteer-cluster/blob/9bfa632565dd3eb496f0fb5f2c2a7a21368b4d4e/src/Worker.ts#L112), even after an error. Did this not work for you?

**Comment by mtatarau90** [comment]
seems that not works if puppeteer return timeout error.

**Comment by thomasdondorf** [comment]
Could you share your code and your debug log (via `DEBUG='puppeteer-cluster:*' node examples/minimal`)?

**Comment by mtatarau90** [comment]
sorry but i can't share my cod, but is very easy to reproduce it.
1. set timeout: 500/1000 to Cluster.lunch
2. devtools = true
3. log your taskerror

You will see that the new tabs are still active, thanks

**Comment by thomasdondorf** [comment]
Just gave it a try. I **cannot** reproduce it. Here is my code: https://gist.github.com/thomasdondorf/2b5288fa014f28c84cad80992bbbab72

The output is:
```
Error crawling https://www.google.com: Timeout hit: 1000
Error crawling https://www.wikipedia.org: Timeout hit: 1000
Error crawling https://github.com/: Timeout hit: 1000
```

The pages are closed correctly.

**Comment by mtatarau90** [comment]
So strange, seems that works perfectly, and of course my projects works fine, is strange, perhaps was a chrome issue. Can you close the issue ? thanks

**Comment by thomasdondorf** [comment]
Alright, if you have problems again feel free to reach out :)
