### ISSUE TITLE
Add support for puppeteer-firefox

### ISSUE THREAD

**Issue by shubh453** [thomasdondorf/puppeteer-cluster#112]
Hi,
Really love your project, have successfully used clustered chrome instances but my requirement is also to include Firefox. As puppeteer is developing 'puppeteer-firefox', although it is experimental and soon to be released. I looked into this issue #41 and tried to use it for firefox, it doesn't work. 
Throws this error:
```
(node:3160) UnhandledPromiseRejectionWarning: Error: Unable to get browser page
    at Worker.<anonymous> (C:\Users\hp\Desktop\Project\node_modules\puppeteer-cluster\src\Worker.ts:75:27)
    at Generator.next (<anonymous>)96 (running for 1.2 minutes)
    at fulfilled (C:\Users\hp\Desktop\Project\node_modules\puppeteer-cluster\dist\Worker.js:4:58)
    at <anonymous>own (@ 0 pages/second)
```
Can you please help to solve this issue?

**Comment by thomasdondorf** [comment]
Please provide more information on your setup.

I just gave it a try and everything worked as expected (Linux and Windows as well as headless and headful). This is my code: https://gist.github.com/thomasdondorf/307e8151bce327cf907fc4c5e0f47f0a

**Comment by shubh453** [comment]
Thanks for the quick reply.. i tried again to run this code: [https://gist.github.com/shubh453/299159d9c48c3aa17e21b8ccad36e13a.js](url) and problem still persists.
I am using puppeteer-firefox- 0.4.2 and running on Windows 10, it seems to open the browser for a split second and automatically get closed, happens for multiple times until `(node:3160) UnhandledPromiseRejectionWarning: Error: Unable to get browser page` appears.

**Comment by thomasdondorf** [comment]
Just had a quick look at your code and you are using `forEach` with `async`/`await` which [is not a good idea](https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop). I cannot say for sure that this is the problem, but that is also a lot of code ;)

Can you check if the minimal example I linked to above is working for you.

**Comment by shubh453** [comment]
Thanks for the tip on using `forEach` with `async`/`await`, I tried using `for...of` which didn't work, then i tried your minimal example which also throws the same error. Although when i tried running it without cluster, it worked perfectly. Finally i ran it in [debug mode](https://github.com/thomasdondorf/puppeteer-cluster#debugging), i found this error `TypeError: browser.createIncognitoBrowserContext is not a function` which makes me realize that maybe this issue is related to firefox nightly build. So i ran it in incognito without cluster and it also throws the above error.
So my best guess is that it is not related to puppeteer-cluster and is related to puppeteer-firefox experimental build. Thanks for your input. Just one query though, what is the necessity of using incoginto window/page?

**Comment by thomasdondorf** [comment]
Which version of `puppeeter-firefox` are you using? It seems that your version is outdated. According to [this page](https://aslushnikov.github.io/ispuppeteerfirefoxready/) the function `browser.createIncognitoBrowserContext` should exist.

> what is the necessity of using incoginto window/page?

`CONCURRENCY_PAGE` does not call that function and simply uses pages. You can try if it works with that setting.
`CONCURRENCY_CONTEXT` and `CONCURRENCY_BROWSER` use `createIncognitoBrowserContext ` to provide an isolated environments without having to restart the browser every time.

**Comment by shubh453** [comment]
> Which version of `puppeeter-firefox` are you using? 
I was running puppeteer-firefox 0.4.2, which was in fact not the latest version. I updated it and fixed the error.
I am going to close this issue. Thanks for your time.
