### ISSUE TITLE
Unhandled exception thrown by SystemMonitor

### ISSUE THREAD

**Issue by zenwarr** [thomasdondorf/puppeteer-cluster#113]
Hello! Unfortunately, I've faced a problem when this module runs in some environments (I'm using node 8 LTS).

```
TypeError: Cannot read property 'length' of undefined
    at SystemMonitor.calcLoad (node_modules/puppeteer-cluster/dist/SystemMonitor.js:35:36)
    at Timeout.interval.setInterval [as _onTimeout] (node_modules/puppeteer-cluster/dist/SystemMonitor.js:23:56)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

Code that throws the error:

```javascript
const cpus = os.cpus();
for (let i = 0, len = cpus.length; i < len; i += 1) {
    const cpu = cpus[i];
    for (const type in cpu.times) {
        totalTick += cpu.times[type];
    }
    totalIdle += cpu.times.idle;
}
```

And the problem is related to the fact that `os.cpus` can sometimes return `undefined`: https://github.com/nodejs/node/issues/19022

**Comment by thomasdondorf** [comment]
Thanks for reporting. This behavior is not even documented in the Node.js docs.

Just pushed a fix, which also improves startup time (by not starting the system monitoring) if the monitoring is disabled.
