### ISSUE TITLE
Is there are a way to open a cluster of non-headless instances?

### ISSUE THREAD

**Issue by charlie632** [thomasdondorf/puppeteer-cluster#114]
The page I need to crawl does not work in headless mode, and I would like to launch multiple instances of my script. Is this possible?

**Comment by thomasdondorf** [comment]
Sure, just pass `headless: false` as puppeteer [option](https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions) to the cluster like this:

```js
const cluster = await Cluster.launch({
    // ...
    puppeteerOptions: {
        headless: false
    }
});
```

**Comment by charlie632** [comment]
Thanks!
