### ISSUE TITLE
Browser settings

### ISSUE THREAD

**Issue by strarsis** [thomasdondorf/puppeteer-cluster#116]
Where/how can the browser settings be set for the all browsers in the cluster, 
like for setting the [`userAgent`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-browseruseragent)?

**Comment by thomasdondorf** [comment]
It's the same as in puppeteer: https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/docs/api.md#pagesetuseragentuseragent
