### ISSUE TITLE
Is it possible to monitor element changes?

### ISSUE THREAD

**Issue by pvijaysimha** [thomasdondorf/puppeteer-cluster#117]
I'm trying to fetch about 400 pages from a website and monitor each page changes.

Following is the code I'm trying to write:
```js
const {Cluster} = require('puppeteer-cluster');

var cheerio = require('cheerio');


const monitorPage = async function (urls) {
    try {

        const cluster = await Cluster.launch({
            concurrency: Cluster.CONCURRENCY_CONTEXT,
            maxConcurrency: 2,
        });
        const extractTitle = async ({page, data: url}) => {
            await page.setBypassCSP(true);
            await page.goto(url);
            page.on('console', consoleObj => console.log(consoleObj.text()));

            await page.evaluate(() => {
                try {
                    const test = document.querySelector('.allChatHolder.chatMsgContainer-in');

                    const observer = new MutationObserver(
                        function (mutations) {
                            console.log(test.innerHTML);
                            mutations.forEach(
                                function (mutation) {
                                    mutation.addedNodes.forEach(
                                        function (node) {
                                            console.log('The added chat' + node.innerHTML);
                                        }
                                    );
                                    mutation.removedNodes.forEach(
                                        function (node) {
                                            console.log('The removed chat' + node.innerHTML);
                                        }
                                    );
                                }
                            );
                        }
                    )
                    const config = {
                        attributes: true,
                        childList: true,
                        characterData: true,
                        subtree: true
                    }
                    observer.observe(test, config)
                }catch(err){
                    console.log(err);
                }
            })


        }

        for (var i = 0; i < 2; i++) {
            console.log("urls[i]  " + urls[i])
            cluster.queue(urls[i], extractTitle);
        }
        // cluster.queue('http://www.google.com/');
        // cluster.queue('http://www.wikipedia.org/');
        // many more pages

        // await cluster.idle();
        // await cluster.close();


    } catch (err) {
        console.error(err);
    }
}

module.exports = monitorPage;
```

For some reason unable to print data inside observer.
I'm able to get this working using Puppeteer when I run individual page.
Anyone working/worked on such a scenario?

**Comment by thomasdondorf** [comment]
This is a very vague question, I'm not even sure it is related to this library. Can you provide an example how your code works without puppeteer-cluster, then I can help to to figure out how to get it to work with a pool.

**Comment by pvijaysimha** [comment]
Thanks for the reply.

`'use strict';

const puppeteer = require('puppeteer');

const html = `
<!doctype html>
<html>
  <head><meta charset='UTF-8'><title>test</title></head>
  <body><span class='ss1'>1</span></body>
  <script>
    let counter = 1;
    setInterval(
      () => { document.querySelector('.ss1').textContent = ++counter; },
      1000
    );
  </script>
</html>
`;

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.setBypassCSP(true);
    await page.goto('about:blank');
    await page.setContent(html);

    page.exposeFunction('puppeteerMutationListener', puppeteerMutationListener);

    await page.evaluate(() => {
      const target = document.querySelector('.ss1');
      const observer = new MutationObserver((mutationsList) => {
        for (const mutation of mutationsList) {
          window.puppeteerMutationListener(
            mutation.removedNodes[0].textContent,
            mutation.addedNodes[0].textContent,
          );
        }
      });
      observer.observe(
        target,
        { childList: true },
      );
    });
  } catch (err) {
    console.error(err);
  }
})();

function puppeteerMutationListener(oldValue, newValue) {
  console.log(`${oldValue} -> ${newValue}`);
}`

This is the logic I'm currently using to monitor the changes on a page.
I'm trying to read text/node changes of an element(s) in  hundreds of such pages of a website, 

I ended up with puppeteer-cluster because monitoring 400 pages resulted in loop resulted in memory issues.

I'm really new to web scraping stuff. So, please excuse me If I don't make sense at all.

**Comment by thomasdondorf** [comment]
That's a lot of code and I just skimmed though it. Do you want to actually monitor 400 pages in parallel or is this a job that takes a few seconds and then you want to proceed to the next page?

Can you provide a minimal example that shows what is not working?

**Comment by pvijaysimha** [comment]
I actually want to run monitor 400 pages. All the pages will have a chat room each.
So, I need to keep track of all the new messages coming on to the chat window from different different users.
I'll try to provide a minimal example.

**Comment by pvijaysimha** [comment]
Following is the prototype of what exactly I'm looking to achieve
`const puppeteer = require('puppeteer');

(async function main() {
    //Here I'll have an get array of URLs that I loop through and monitor
    for(var i = 1 ; i<10 ; i++){
        monitorPage('http://cdafbaa9.ngrok.io') //Using just one chat room for testing purpose
    }
})();

async function monitorPage(url) {
    try {
        const browser = await puppeteer.launch();
        const [page] = await browser.pages();

        await page.setBypassCSP(true);
        await page.goto(url);
        // await page.setContent(html);

        page.exposeFunction('log', log);

        page.on('console', consoleObj => console.log(consoleObj.text()));

        await page.evaluate(() => {
            const target = document.querySelector('section#chatroom');
            const observer = new MutationObserver(
                function(mutations) {
                    mutations.forEach(
                        function (mutation) {
                            mutation.addedNodes.forEach(
                                function(node) {
                                    log('The added chat', node.innerHTML);
                                }
                            );
                        }
                    );
                }
            )
            const config = {
                childList: true,
                subtree: true
            }
            observer.observe(target, config)
        })
    } catch (err) {
        console.error(err);
    }
}

function log(msg , node){
    console.log(msg);
    console.log(node);
}
`

For the content change I'll just add some messages here :
http://cdafbaa9.ngrok.io

Thanks

**Comment by thomasdondorf** [comment]
If you want to handle 400 pages in parallel (if I understood you correct), you need a machine to handle 400 pages/browsers in parallel. You'll need a lot of memory/CPU for that.

Then set your pool size to 400 workers and you can run the code you want and listen for changes. At the end of your task function you can do something like `await new Promise(resolve => {})` to never close the page.

**Comment by thomasdondorf** [comment]
Closing this for now, feel free to re-open with a concrete question.
