### ISSUE TITLE
How to set different puppeteerOptions in one cluster

### ISSUE THREAD

**Issue by dxxzst** [thomasdondorf/puppeteer-cluster#118]
I want to use a different proxy for each browser，so I need to pass different args parameters。
But I see that the cluster can only be initialized once，how to solve my problem？

**Comment by Bitomancer** [comment]
same problem

**Comment by thomasdondorf** [comment]
This is a popular request. I will let this issue open as I will implement this in the future. Right now there is already a way to do this via a [custom concurrency](https://github.com/thomasdondorf/puppeteer-cluster#concurrency-implementations), but I don't recommend using this at the moment as the API for this will likely change.

**Comment by vincenthawke** [comment]
> This is a popular request. I will let this issue open as I will implement this in the future. Right now there is already a way to do this via a [custom concurrency](https://github.com/thomasdondorf/puppeteer-cluster#concurrency-implementations), but I don't recommend using this at the moment as the API for this will likely change.

Do you have any simple examples of code where proxy for each browser instance was implemented? I would prefer a proxy setting that sticks with every instance but will settle for a proxy-switcher that takes a proxy from pool of proxy settings and assigns one to the browser every time a new task is taken form the queue. Either would work for my test project but for the future would be nice if we could specify it more strictly. Thank you.

**Comment by lazybotter** [comment]
> > This is a popular request. I will let this issue open as I will implement this in the future. Right now there is already a way to do this via a [custom concurrency](https://github.com/thomasdondorf/puppeteer-cluster#concurrency-implementations), but I don't recommend using this at the moment as the API for this will likely change.
> 
> Do you have any simple examples of code where proxy for each browser instance was implemented? I would prefer a proxy setting that sticks with every instance but will settle for a proxy-switcher that takes a proxy from pool of proxy settings and assigns one to the browser every time a new task is taken form the queue. Either would work for my test project but for the future would be nice if we could specify it more strictly. Thank you.

I would like this too :-)

**Comment by vincenthawke** [comment]
> > > This is a popular request. I will let this issue open as I will implement this in the future. Right now there is already a way to do this via a [custom concurrency](https://github.com/thomasdondorf/puppeteer-cluster#concurrency-implementations), but I don't recommend using this at the moment as the API for this will likely change.
> > 
> > 
> > Do you have any simple examples of code where proxy for each browser instance was implemented? I would prefer a proxy setting that sticks with every instance but will settle for a proxy-switcher that takes a proxy from pool of proxy settings and assigns one to the browser every time a new task is taken form the queue. Either would work for my test project but for the future would be nice if we could specify it more strictly. Thank you.
> 
> I would like this too :-)

How far have you got?:)

I just found how to make proxy authentication work with http and https pages with only pupeteer, no cluster library. 

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
    headless: true,
    args: ['--proxy-server=IP:PORT']
  });
  
  const page = await browser.newPage();
  await page.authenticate({ 
      username: 'imperialposter' , 
      password:'WP5DCOV2U5TIQIKYR4PEJLQQ' 
  });

  await page.goto('https://domain.com');
  await page.screenshot({path: 'example.png'});  //just to see faster what loaded
  await browser.close();
})();
```

**Comment by vincenthawke** [comment]
> I would like this too :-)

How far have you got?:)

I just found how to make proxy authentication work with http and https pages with only pupeteer, no cluster library. 

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
    headless: true,
    args: ['--proxy-server=IP:PORT']
  });
  
  const page = await browser.newPage();
  await page.authenticate({ 
      username: 'username' , 
      password:'password' 
  });

  await page.goto('https://domain.com');
  await page.screenshot({path: 'example.png'});  //just to see faster what loaded
  await browser.close();
})();
```

**Comment by lazybotter** [comment]
I ended up just coding my own cluster pool, probably not as good as this module but works ok. I used the “cluster” module to fork new processes/workers.

**Comment by vincenthawke** [comment]
> I ended up just coding my own cluster pool, probably not as good as this module but works ok. I used the “cluster” module to fork new processes/workers.

I don't know if you encountered this problem but my proxy implementation had a problem that my real IP was leaking through the webRTC and then I went over request/minute limit for my own IP which caused a temporary ban form the site I parsed. How did you prevent webRTC leaking in headless:true mode without extensions?

**Comment by therepo90** [comment]
any update on this? im using `proxy-chain` and it doesnt work with current solution

**Comment by braeden123** [comment]
@therepo90 Could you elaborate on how/what you used to do the one to many proxy redirect?

**Comment by therepo90** [comment]
point puppeter proxy to your custom server that consumes request and makes request to server created by proxy-chain

**Comment by kids-return** [comment]
I think I can set up a callback function before browser starts
Call the proxy dynamically in this function
Then set it to browser's args

**Comment by kids-return** [comment]
E.g.
```js
        browserStartBefore: function (puppeteerOptions) {
            proxy = getProxy();
            puppeteerOptions.args.push(proxy);
        },
```
Is this feasible?

**Comment by brunogaspar** [comment]
@kids-return Did you manage to do something?

Interested in working on something like this as well

**Comment by HugoPoi** [comment]
I have implemented something, if someone brave can review the code :+1:

**Comment by HugoPoi** [comment]
Beside the #235, I have implemented a custom concurrency here https://github.com/NikolaiT/se-scraper/pull/61

**Comment by ejames17** [comment]
@dxxzst  did you ever figure this out what option did you end up going with?

**Comment by chrisfranko** [comment]
Ah yea i cant use this if I cant use a different proxy per instances

**Comment by thomasdondorf** [comment]
Version `0.20.0` (just released) supports options per browser.

Big thanks @HugoPoi for implementing it. (#235)

**Comment by chrisfranko** [comment]
Whaaaat epic
