### ISSUE TITLE
Looking for a simple example of getting a list of webpages with id from postgresql then store the website content back into postgresql?

### ISSUE THREAD

**Issue by majestique** [thomasdondorf/puppeteer-cluster#119]
I'm looking to grab webpage content(not print screen/pdf, just the html/ajax content) from a list of 15k urls (no need to spider/discover, I have the direct links), and I need to store just the content back into a postgresql table. 

Thanks in advance!

**Comment by thomasdondorf** [comment]
I might have just answered your question on stackoverflow: https://stackoverflow.com/a/55268221/5627599
