### ISSUE TITLE
Wait for ajax to load first

### ISSUE THREAD

**Issue by majestique** [thomasdondorf/puppeteer-cluster#121]
There's a plugin that waits for xhr to load https://github.com/jtassin/pending-xhr-puppeteer
Is this a reliable method to wait for all ajax content to load? Would it work with `puppeteer-cluster`?

I'm wondering if there's a more reliable method to wait for ajax to load? I prefer not waiting for a selector to load since I have many different sites, and this would require me to configure for each ajax site as discussed here: https://stackoverflow.com/questions/51066987/puppeteer-how-can-i-wait-for-ajax-request-and-process-the-result

Here's a sample page that takes a while to load:
https://cportal.lendingqb.com/Onlineapp2/GetRate.aspx?siteid=9f4ab128-33f9-4d14-9b11-18c96aef1fb3&sLPurposeT=0&aOccT=0&sProdSpT=0&sLAmtCalc=400000&sPurchPrice=300000&sSpZip=92708&sSpState=CA&sSpCounty=Orange&sProdImpound=1&sRLckdDays=45&sCreditScoreType1=760

Thanks in advance!

**Comment by thomasdondorf** [comment]
I recommend you ask general questions regarding puppeteer in the puppeteer repository or on stackoverflow.

I haven't tested the plugin, but I'm pretty sure it should work as it just works on the `page`. So put it in your `task` function and you should be fine.
