### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by acosonic** [thomasdondorf/puppeteer-cluster#122]
Hi, I'm very happy with puppeteer-cluster, but 

I can't find example for statistics, can you please help with some?

FYI my result is: 14k  URL's with 8 worker threads in 1hr :)

**Comment by thomasdondorf** [comment]
Glad to hear that :)

14k URLS in 1hr with 8 workers makes 0.49 jobs (`14000 / 8 / 60 / 60`) per second+worker or 2.05s per job, which is very much on par with my results so far. From my experience, depending on the task (DOM extractions, screenshot, etc.) and size of the pages you are crawling you will roughly need between 1-6 seconds per job.

I posted a run with some statistics with 2 concurrent workers in [this thread](https://github.com/thomasdondorf/puppeteer-cluster/issues/25#issuecomment-423295160). The run processed 0.19 jobs per second and worker (or 5.3s per job).

But in general, it is hard to compare different kind of tasks. The crawling time might also vary very much for bigger websites.

Hope this helps you a bit :)

**Comment by thomasdondorf** [comment]
Closing this as there is already a similar thread. Feel free to reopen if anything is unclear.
