### ISSUE TITLE
Blocking specific network requests to improve performance

### ISSUE THREAD

**Issue by vincenthawke** [thomasdondorf/puppeteer-cluster#123]
Hey! 
Great work on this library, it is my first try at palatalization. I started by testing your alexa code sample and wanted to share a snippet I found that blocks style sheets, fonts and images and make the test case of [alexa parsing](https://github.com/thomasdondorf/puppeteer-cluster/blob/HEAD/examples/alexa-1m.js) almost 2x faster. 

```
    await page.setRequestInterception(true);
    page.on('request', (request) => {
        if (['stylesheet', 'font', 'image'].indexOf(request.resourceType()) !== -1) {
            request.abort();
        } else {
            request.continue();
        }
    });
```

I just added this after `await cluster.task(async ({ page, data: url }) => {` 

Thank you for your library!

**Comment by thomasdondorf** [comment]
Thanks for leaving the comment. :) I'll add a link to this issue from the example on how to speed the crawling up.
