### ISSUE TITLE
How can I overrightPermission in cluster ?

### ISSUE THREAD

**Issue by poochai97** [thomasdondorf/puppeteer-cluster#134]
How can I overrightPermission in cluster ?
I want to set permission for all Incognito page to crawl data from it like puppeteer
  await context.overridePermissions('https://www.facebook.com/', ['notifications']);
But in puppeteer-cluster i don't know how to get browser or context to override this.
Tks you so much :D

**Comment by thomasdondorf** [comment]
You can get the browser of the page via `page.browser()` and from there on you should be able to set the permissions.

**Example:**
```js
const context = page.browser().defaultBrowserContext();
context.overridePermissions(/* ... */);
```
Feel free to reopen if anything is unclear.
