### ISSUE TITLE
Best Practice for Recursion

### ISSUE THREAD

**Issue by Stoley777** [thomasdondorf/puppeteer-cluster#136]
Hey Tom, Thanks for all the hard work on the project. I was working in a silo, and essentially began to make something similar to this using generic-pool, but that was going to be a huge delay. It's encouraging to see you've solved a lot of the problems of clustering puppeteer.

I had one question, for what your recommendation is for recursion within the queue.

I had used recursion in puppeteer with a function. Would you recommend this in a task definition, ie function calls itself within the same task?

Or would you recommend re-queuing the function back to the cluster, by adding a new job?

Currently the function checks if there's more pages and modifies the input url and then adds a new queue to the cluster:

```
const extract = async ({ page, data: dataJson }) => {
     // scrape a website url found in dataJson.url
    // check if there's more pages, modify dataJson.url for the next page querystring 
   // recursion logic, then if true
      cluster.queue(dataJson, extract); 
      break;
    }
  }; //end Extract task function
```

What I noticed was, that I expected 50,000 pages to output 50,000 files, but results were fewer, @ only 30,000 with recursion by re-queuing.

**Comment by Stoley777** [comment]
figured it out.

**Comment by thomasdondorf** [comment]
Easiest way is to always queue new jobs via `cluster.queue` :)
