### ISSUE TITLE
Monitor Flag

### ISSUE THREAD

**Issue by scottk** [thomasdondorf/puppeteer-cluster#146]
Is it possible to set the monitor status for each thread, and if not, to add it as a feature request?

I'd like to do something similar to console logs for each page to see how things are progessing within my application. Thanks!

**Comment by thomasdondorf** [comment]
Can you give an example? Right now monitor should show the URL for each worker.

If you want to read on which worker is handling which job you can access the `worker.id` inside the task like this:

```js
await cluster.task(async ({ page, data, worker }) => {
    console.log(worker.id);
});
```

See the [docs](https://github.com/thomasdondorf/puppeteer-cluster#clustertasktaskfunction) for more information. Does this solve your problem? :)

**Comment by thomasdondorf** [comment]
Feel free to reopen if anything is unclear.
