### ISSUE TITLE
keep pages open and do tasks by interval 

### ISSUE THREAD

**Issue by alirezadarban** [thomasdondorf/puppeteer-cluster#147]
Hi!
I have a strange process! I have to read data from about 70 pages, every second.  Opening the pages wastes a lot of time and I shouldn't lose any data. I should open pages once and keep them open, then scratch page and read data. How can I do that?

**Comment by thomasdondorf** [comment]
As long as the task function does not resolve, the page is kept open.

The following example will keep the page open for 10s. So you could put your code inside that promise and call resolve when you are done. This will keep the opened as long as you need it:

```js
await cluster.task(async ({ page, data }) => {
    await page.goto('...');
    // ... do more stuff

    await new Promise(resolve => {
        setTimeout(() => {
            resolve(); // if you never call resolve, the page will always stay open
        }, 10000);
    });
});
```

Feel free to reopen if anything is unclear.

**Comment by alirezadarban** [comment]
Thanks a lot man. I'll check it soon and notice you if I need.
