### ISSUE TITLE
Please ask questions on stackoverflow

### ISSUE THREAD

**Issue by thomasdondorf** [thomasdondorf/puppeteer-cluster#150]
##### Tag them with the tag [`puppeteer-cluster`](https://stackoverflow.com/questions/tagged/puppeteer-cluster) (and probably also with `puppeteer`, `node.js`, etc.)

---

As there are more and more [questions](../issues?q=label%3Aquestion) being asked in this repository, of which some are not even related to this library, I kindly ask everyone to ask questions on stackoverflow. I created the tag `puppeteer-cluster` for this library, which I'm watching ([I'm active on stackoverflow](https://stackoverflow.com/users/5627599/thomas-dondorf?tab=profile)).

Although you are using this library, many problems are not related to this library and instead to puppeteer or even JavaScript itself. You might not even need my help to solve the problem in many cases.

### Please keep using the issues for:

- Feature requests, ideas or any other kind of discussion regarding this library
- Issues/bugs related to this library

### Thanks everyone! 😊

**Comment by iamanas20** [comment]
Hello,
how can I use the equivalent to "puppeteer.connect" instead of puppeteer.launch? 
I want to connect to https://www.browserless.io to use puppeteer on a server, how can I do that using 'puppeteer-cluster'?
Thank you!

**Comment by kathirks2003** [comment]
How does the browser restart itself when it is crashed?
