### ISSUE TITLE
How to distinguish tabs connections in proxy?

### ISSUE THREAD

**Issue by therepo90** [thomasdondorf/puppeteer-cluster#152]
Hey thanks for this nice tool.

How to distinguish connections between pages im browsing in proxy server? Lets say Im using proxy server and  open 10 pages at the same time. One page can contain multiplel resources but it refers to this tab. 
ConnectionId is not the thing. Its just some variable incrementing. Is there any id like socket/connection that belongs to one specific opened page?

**Comment by thomasdondorf** [comment]
I'm not sure if I fully understand you. Bu I guess you are trying to provide proxy settings per browser instance?

This is not yet implemented. It's already discussed in here, though: #118 

Feel free to reopen in case that was not the problem.

**Comment by thomasdondorf** [comment]
Just saw you already commented there. Sorry, I missed that comment...

I cannot give any concrete update on the status right now. I might implement it in the future, but cannot give any dates, sorry.
