### ISSUE TITLE
Different outputs for Firefox and Chrome pupeeters 

### ISSUE THREAD

**Issue by vedantseta** [thomasdondorf/puppeteer-cluster#163]
When I use queue multiple URLs for Firefox, I see them open in multiple tabs in same window.
The same test for Chromium gives multiple windows, one with each URL.

I agree that this question would be out of scope of this project. However shouldn't both outputs be consistent?

**Comment by thomasdondorf** [comment]
Can you show a minimal code sample?

But I think that, yes, this question is out of scope for the project and better belongs on the puppeteer repository itself. Keep in mind that `puppeteer-firefox` is still experimental AFAIK.
