### ISSUE TITLE
Unhandled Exception - failed to launch browser

### ISSUE THREAD

**Issue by chrisrosa418** [thomasdondorf/puppeteer-cluster#167]
Hey Thomas,

I am working on a project and hit a small snag, was wondering if you could lend a hand.  

I have a program, that fetches JSON data, feeds the JSON response into a queueing mechanism, and then queueing mechanism opens a puppeteer instance (code below for the puppeteer instance) which does a variable find/ replace and takes a screenshot.  

```
navigationSource = 'url';

FunctionName: function(Data, var2, var3) {        
    return new Promise(function(resolve, reject){
        (async () => {
          const cluster = await Cluster.launch({
            concurrency: Cluster.CONCURRENCY_BROWSER,
            puppeteerOptions: { args: ['--no-sandbox'] },
            maxConcurrency: 2,
            workerCreationDelay: 500,
            retryLimit: 1,
            timeout: 5000,
          });
      
          await cluster.task(async ({ page }) => {
            await page.goto(navigationSource);

            await page.evaluate(x => {
                data = x;
                replaceRCValues(data['content'], rcScoreValues);
            }, Data);


            await page.emulateMedia('screen');
            await page.pdf({ path: var2 + var3,
                      format: 'letter',
                      printBackground: true,
                            margin: {
                          top: ".2in",
                          bottom: ".1in",
                          left: ".75in",
                          right: ".75in"
                      },
                      });            
          });

          // In case of problems, log them
          cluster.on('taskerror', (err, data) => {
            console.log(`DEBUG - Error with cluster ${data}: ${err.message}`);
          });

          cluster.queue();            
      
          await cluster.idle();
          await cluster.close();

          resolve({success:true})
        })()
        .catch(err => {
          console.log(`DEBUG - CAUGHT ERROR FROM MainFunction -- ${err}`)
          reject({success:false})
        })
        
      });    
  },
```

**Issue**
I was first running into issues directly with puppeteer, in that the browser instance was failing to launch due to resource issues, and I was getting a `timeout error 30000ms exceeded`

I then looked into your program, to handle said error, and my success rate skyrocketed with the way you cluster the puppeteer instances, thank you for that.  

I still however, am getting the following error

```
(node:64000) UnhandledPromiseRejectionWarning: Error: Unable to launch browser for worker, error message: waiting for target failed: timeout 30000ms exceeded
    at Cluster.<anonymous> (/Users/crosa/Cylance_Repo/CylanceReportsTwoOhNew/reportProcessor/node_modules/puppeteer-cluster/dist/Cluster.js:129:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/crosa/Cylance_Repo/CylanceReportsTwoOhNew/reportProcessor/node_modules/puppeteer-cluster/dist/Cluster.js:5:65)
(node:64000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tried to put various catch blocks in my code, and I also changed `cluster.on('taskerror', (err, data))` to `cluster.on('UnhandledPromiseRejectionWarning', (err, data))` in hopes of handling those errors, but that was un-successful too.  

**Solution I am looking for**
Ultimately, I'd like to 
(1) Attempt to ingest JSON data and push to puppeteer for variable find/replace and screenshot generation
(2) If the browser fails, retry once.  If it fails the second time, catch the error and reject it, so that I can update the report attempt as failed

Any thoughts on how I can handle that rejection?  So that I can pivot off of its failure

**Bug Number 2**
I would like the browser to timeout after 5000ms rather then 30000ms, as you can see by my above code, there is a timeout set for 5000ms, but regardless I get the 30000ms timeout for the browser.  Any thoughts there?  I tried to add `puppeteerOptions: { args: ['--no-sandbox'], timeout:5000 },` as well and that did not work.  Still timesout at 30000ms

**Comment by thomasdondorf** [comment]
The `timeout` in `options` is for the full task, you can still set custom timeouts to `page.goto` (and other puppeteer functions) as you want. Regarding the `waiting for target failed: timeout 30000ms exceeded`. When exactly does that happen? Can you provide a minimal example, please?

Tagging this as question, as this does not really look like a bug to me. Feel free to re-open or re-tag to continue the discussion.
