### ISSUE TITLE
Usage with JEST tests in different files?

### ISSUE THREAD

**Issue by joacim-boive** [thomasdondorf/puppeteer-cluster#17]
A common use-case would be to have many different tests spread out over multiple files.

This seems to be exactly what I need to speed up my tests - but I don't understand how to utilise it to run tests in different files in parallell.

Ex;
One test suite in home/__tests__/__e2e__/LoginPage.test.js
Another test suite in loan/__tests__/__e2e__/OverviewPage.test.js

I understand I could use it within the same test suite - but what about running different test suites in parallel?

**Comment by thomasdondorf** [comment]
I have not used puppteer in any Jest tests so far (aside from testing my own library). Does [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) not already handle this or does the library execute the tests sequentially if you use puppteer?

Maybe this might be a better question to ask over at the jest-puppteer, but maybe @neoziro can help us :)

**Comment by joacim-boive** [comment]
My bad - I only thought it wasn't run in parallel but doing the test in headfull mode shows multiple instances of browsers.

So, all is well. :)

**Comment by neoziro** [comment]
@thomasdondorf I have just discovered that project, I think Jest Puppeteer is not compatible with it. But in future it could ;)

**Comment by thomasdondorf** [comment]
Thanks for answering @neoziro. If you ever plan on using this library for jest-puppteer, I'm happy to help :)

**Comment by seyfer** [comment]
@gregberge @thomasdondorf is it compatible now?
