### ISSUE TITLE
Supplying null throws unhandled error

### ISSUE THREAD

**Issue by CKunhardt** [thomasdondorf/puppeteer-cluster#178]
Line 19 of Job.js checks to see if `this.data !== undefined` before checking `typeof this.data.url === 'string'`. However, in my case, I am supplying `null` to `cluster.execute` in the form of `cluster.execute(null, myTaskFunc)` as I don't need to pass any data into the task function, but don't want to define the task function inside of the call to `cluster.execute`. As a result, `this.data !== undefined` is true, but the program throws an unhandled error when trying to access `this.data.url`, as `this.data` is null.

I would recommend changing the `this.data !== undefined` check to something along the lines of just checking the truthiness of `this.data`, so that all falsy values are caught (including `''`!)

For now, I'm passing in an empty object, and that seems to work as a stop-gap measure.

**Comment by thomasdondorf** [comment]
Correct, that's a bug. That check should be just `this.data`, not `this.data !== undefined`. Do you want to make a pull request?
