### ISSUE TITLE
Getting Repeated “Navigation failed because browser has disconnected” errors.

### ISSUE THREAD

**Issue by alexmacarthur** [thomasdondorf/puppeteer-cluster#179]
Hi! Thanks for the package. I posted this to StackOverflow, but also going to post here in case it's of value & others have experienced it. 

https://stackoverflow.com/questions/57155629/getting-repeated-navigation-failed-because-browser-has-disconnected-errors-whe

Basically, whenever I try to use this on a DigitalOcean droplet w/ a decent-sized set of resources, I'm getting this "Navigation failed because browser has disconnected" error over and over. Locally, it usually works just fine, but once I deploy it, it doesn't. I've been assuming it's resource-related, but can't nail that down for sure. 

Any ideas?

**Comment by alexmacarthur** [comment]
This seems to be mostly resolved if I limit my `maxConcurrency` to `2, which makes me think it's an issue related to the machine on which I'm running it -- performance stuff. I'm using a Digital Ocean droplet w/ 2 CPUs and a GB of RAM.

**Comment by thomasdondorf** [comment]
You might want to have a look at this [answer on stackoverflow](https://stackoverflow.com/a/57295869/5627599) to test whether its a resource problem.
