### ISSUE TITLE
Refresh browsers instances after a while

### ISSUE THREAD

**Issue by Kikobeats** [thomasdondorf/puppeteer-cluster#194]
Browsers instances tend to grow using CPU/memory over time with no clear reasons. 

A good way to keep resources under control can be gracefully shutdown idle browser instance after a while and re-restart then to have a fresh instance again.

Just for inspiration, at [browserless](https://browserless.js.org) I was to add a more aggressive way for doing that under unexpected browser disconnect: https://github.com/Kikobeats/browserless/blob/master/packages/browserless/src/index.js#L18.

Also, browserless.io docker image is doing a similar thing `CHROME_REFRESH_TIME` flag: https://docs.browserless.io/docs/docker.html#chrome-refresh-time.

**Comment by Kikobeats** [comment]
For mitigating stranges behavior there, I adopt a "zero downtime strategy", where I consider `puppeteer-cluster` is hanging after a time, and fall back into a single `puppeteer` instance just for resolving the task

```js
const takeScreenshot = require('@browserless/screenshot')
const pTimeout = require('p-timeout')
const ms = require('ms')

const debugTime = require('../debug-time')('microlink-api:screenshot')
const { createBrowser } = require('./puppeteer')
const logError = require('../log-error')
const cluster = require('./cluster')

const SCREENSHOT_TIMEOUT = ms('8s')

const takeScreenshot = async (url, opts) => {
  try {
    const clusterTime = debugTime({ id })

    // after 8s we consider puppeter-cluster
    // instance is hanging
    const buffer = await pTimeout(
      cluster.screenshot(url, opts),
      SCREENSHOT_TIMEOUT
    )
    clusterTime()
    return buffer
  } catch (err) {
    logError(err, {
      level: 'warning',
      method: 'getBrowserless',
      url
    })

    // we fallback into a single puppeteer instance
    const browserlessTime = debugTime({ id }, 'fallback', err.message)
    const browser = await createBrowser()
    const page = await browser.newPage()
    const buffer = await takeScreenshot(page)(url, opts)
    browserlessTime()

    // we kill the instance since `puppeteer-cluster` will ready
    // for serving the next petition
    browser.close()
    return buffer
  }
}
```

If the `puppeteer-cluster` instances are refreshed after a time, then the effect should be the same. Thoughts, @thomasdondorf?

**Comment by thomasdondorf** [comment]
Sounds like #84, right? Basically, after an instance has been used for X times, restart the browser and continue.

**Comment by Kikobeats** [comment]
Yes 🙂

**Comment by thomasdondorf** [comment]
Closing this then, as it's a duplicate.
