### ISSUE TITLE
workerCreationDelay not available if there is an IDLE worker

### ISSUE THREAD

**Issue by camillake** [thomasdondorf/puppeteer-cluster#195]
With the following settings (example).
- maxConcurrency: 2,
- workerCreationDelay: 5000,
- 4 task in queue (the task will finish in 2 secs).

Two worker execute the task in the beginning. 
The next worker execute the task once any worker is idle.

Currently, puppeteer-cluster ignore **workerCreationDelay** if any idle worker.
 Any next worker should wait for **workerCreationDelay**.

**Comment by thomasdondorf** [comment]
`workerCreationDelay` is not the time between two crawling events. It's the time between two instances are started. This is *only* relevant at the start of the cluster and serves the purpose of preventing a network peak right at the start.

You can use `sameDomainDelay` to delay tasks on the same domain. Does this cover your use case? Closing for now, feel free to reopen.
