### ISSUE TITLE
Socks5h not supported

### ISSUE THREAD

**Issue by fishmisswater** [thomasdondorf/puppeteer-cluster#205]
When I add args :"--proxy-server=socks5h:xxx". It shows this:
```
{
error: "net::ERR_NO_SUPPORTED_PROXIES at https://www.xxx.com",
success: false,
etime: 661,
retryCount: 10
}
```
It's normal when I use socks5.

**Comment by thomasdondorf** [comment]
This looks like a puppeteer error and is probably not related to this library. Does it work with puppeteer itself? Closing it for now, feel free to reopen if I'm wrong.

**Comment by milahu** [comment]
socks5h is only needed for curl, where socks5 would leak DNS requests

chromium etc only know socks5, which does not leak DNS requests

see also
https://superuser.com/questions/1762341/does-chromium-not-support-socks5h-with-the-h-in-the-end
