### ISSUE TITLE
How to get the pid of the chromium browser?

### ISSUE THREAD

**Issue by AjaiGanesh** [thomasdondorf/puppeteer-cluster#217]
Hello,

Anyway to get the pid of the chromium browser in all concurrency modes. 

For CONCURRENCY_PAGE I found it in cluster.browser.browser._process._handle.pid

How do I fetch the same for CONCURRENCY_BROWSER and CONCURRENCY_CONTEXT

**Comment by thomasdondorf** [comment]
When you have the page handle, you can call: `page.browser().process()` to get the [browser process](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#browserprocess)
