### ISSUE TITLE
Eventual Resource Leak

### ISSUE THREAD

**Issue by nettad** [thomasdondorf/puppeteer-cluster#229]
After a few months of research and bug fixes on my end I finally stabilized my environment. After about 11 days of uptime I started getting Page Crashed errors. At first it was here and there and I started seeing them in bulks. Restarting the servers fixed the problem.
My Config:
`clusterLauncher.launch({
      concurrency: Cluster.CONCURRENCY_BROWSER,
      maxConcurrency: 2,
      timeout: 300000,
      puppeteerOptions: {
        args: [DISABLE_CORS, '--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
      }
    });`

My Observations:
I noticed that puppeteer cluster starts up 8 chrome instances and these instances stay up the entire time. As time goes by their CPU goes higher and higher every time they are in use.

Question:
Why doesn't puppeteer cluster kill these instances every once in a while and spawn new ones instead?
Is there some config that I missed? My current option, the way I see it, is just to destroy the cluster and reinitialize it myself.
Ideas on something better?

**Comment by thomasdondorf** [comment]
It's currently not implemented: #84
