### ISSUE TITLE
How to best use native Pupeteer instantiation settings?

### ISSUE THREAD

**Issue by wmelton** [thomasdondorf/puppeteer-cluster#231]
Hello,

Great library - very useful!

Question - what is the best way to include Pupeteer settings such as: 

```
await page.setRequestInterception(true);
  page.on('request', request => {
    if (request.resourceType() === 'image')
      request.abort();
    else
      request.continue();
  });
```

Where in the callstack would you put something like this that is meant to be used before the headless browser is created? Can see the original example here: https://github.com/puppeteer/puppeteer/blob/master/examples/block-images.js

**Comment by thomasdondorf** [comment]
Hi, you need to put this inside the `task` function as you get a fresh page every time:

```js
await cluster.task(async ({ page, data: url }) => {
  await page.setRequestInterception(true);
  page.on('...', () => { /* ... */ });
  // ...
});
```
