### ISSUE TITLE
Stopping all running tasks from inside cluster.task

### ISSUE THREAD

**Issue by iamanas20** [thomasdondorf/puppeteer-cluster#234]
Hello, first of all thank you for this amazing library <3
Now my issue is: is there a way I can shutdown all running tasks at once from inside the cluster.task function?

```
await cluster.task(async ({ page, data: url }) => { 
  // if a certain condition is met right here,
  // i want to close all running tasks at once
});
```
Thank you!

**Comment by iamanas20** [comment]
I did use return in `cluster.task` but even though it exists from it when my condition is met, it still goes through it for the remaining tasks that are queued:

```
await cluster.task(async ({ page, data: url }) => {
  if (condition) {
    // scraping stuff
  }else{
    return;
  }
});
```

How can I shutdown all the tasks?

**Comment by thomasdondorf** [comment]
I guess this is the same as #100?

**Comment by AbdaalHassan** [comment]
i also want to stop the cluster .... when it is running ....... 
 i upload a file that have many urls... i want to stop the scrapping for that file too when user need to stop so in short can we stop the cluster task working whenever we want
