### ISSUE TITLE
Run headful mode in the background

### ISSUE THREAD

**Issue by kylewill** [thomasdondorf/puppeteer-cluster#242]
I have several jobs that require running in headless false mode and therefore run them locally on my main machine. 

Because each new page pulls Chromium to the foreground, I can't do anything else while these jobs run.

Is there a way to run headful mode but keep the puppeteer instance in the background?

I tried setting "CONCURRENCY_PAGE" which is better but still pulls the browser to the foreground on each new page.

**Comment by thomasdondorf** [comment]
Sorry, but this is out of scope of this library. There is probably a way to do this somehow by using Windows tricks, but this is a very special edge case, that this library will not support.
