### ISSUE TITLE
Suggestion: Throw error when "maxConcurrency" is non-numeric/undefined

### ISSUE THREAD

**Issue by Discartyptics** [thomasdondorf/puppeteer-cluster#243]
If the "maxConcurrency" option in Cluster.launch is _undefined_ somehow, Cluster never fires any workers and appears to stand still without any errors or warnings.

In my code, I had set the "maxConcurrency" option to a variable, and while refactoring code accidentally set the value to _undefined_ - causing Cluster to never process any queue items.

Maybe Cluster could trigger a warning or error if "maxConcurrency" is set to something non-numeric?

**Comment by thomasdondorf** [comment]
Yes, this looks like an easy fix (simple `if` check in the constructor). Welcoming any pull requests.
