### ISSUE TITLE
Sometimes a pod with puppeteer-cluster does not start

### ISSUE THREAD

**Issue by rabiori** [thomasdondorf/puppeteer-cluster#244]
details here:
https://stackoverflow.com/questions/59749887/puppeteer-cluster-sometimes-cannot-start-in-k8s

**Comment by thomasdondorf** [comment]
I have heard of multiple cases when the cluster does not start, but in no case was this related to this library. I'm assuming this is a fault of the server/hardware/...

If you can investigate the error more and provide more information, feel free to reopen this issue.
