### ISSUE TITLE
Long-term runs of puppteer-cluster

### ISSUE THREAD

**Issue by thomasdondorf** [thomasdondorf/puppeteer-cluster#25]
I'm gonna document some puppeteer-cluster test runs, to see how the different concurrency types and options work together.

Feel free to add your own runs

**Comment by thomasdondorf** [comment]
## Test run 1

#### Abstract
Test run, script extracted the titles of the Alexa 1M over two weeks.

#### Machine
| Property | Value |
|---|---|
| Machine | [Scaleway VM 1S](https://www.scaleway.com/pricing/#anchor_starter), Amsterdam Location |
| Memory | 2 GB |
| CPU | 2 x86-64 |
| Disk | SSD |
| Bandwidth | 200 Mbits/s |

#### Setup
| Property | Value |
|-------------------|-----------|
| Concurrency Type | CONCURRENCY_CONTEXT |
| Workers | 2 |
| Start | 2018-09-06 18:23:39.242 |
| End | 2018-09-20 18:23:41.782 |
| Runtime | 14 days (almost exactly) |
| Pages crawled | 456,026 (@ 0.38 pages/second) |
| Errors | 37,269 (8.17%) |
| Puppeteer crashes | 34 |


<details><summary>Crawling errors</summary>
<p>

```
  11387 net::ERR_NAME_NOT_RESOLVED
   4742 Navigation Timeout Exceeded: 30000ms exceeded
   4466 Timeout hit: 30000
   4447 Execution context was destroyed, most likely because of a navigation.
   4414 net::ERR_CERT_SYMANTEC_LEGACY
   2696 net::ERR_CERT_COMMON_NAME_INVALID
   2438 net::ERR_NAME_RESOLUTION_FAILED
    658 net::ERR_CONNECTION_RESET
    594 net::ERR_CONNECTION_REFUSED
    304 net::ERR_CERT_AUTHORITY_INVALID
    268 net::ERR_TOO_MANY_REDIRECTS
    215 net::ERR_EMPTY_RESPONSE
    196 net::ERR_CERT_DATE_INVALID
    185 net::ERR_ADDRESS_UNREACHABLE
     84 net::ERR_INVALID_REDIRECT
     49 net::ERR_ABORTED
     42 net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
     25 net::ERR_SSL_PROTOCOL_ERROR
     15 net::ERR_CONNECTION_CLOSED
     12 net::ERR_INVALID_RESPONSE
      9 net::ERR_SPDY_PROTOCOL_ERROR
      9 net::ERR_CERT_WEAK_SIGNATURE_ALGORITHM
      6 net::ERR_SSL_UNRECOGNIZED_NAME_ALERT
      2 Protocol error (Page.navigate): Target closed.
      2 net::ERR_CONTENT_DECODING_FAILED
      2 net::ERR_CERT_INVALID
      1 net::ERR_RESPONSE_HEADERS_TRUNCATED
      1 net::ERR_ICANN_NAME_COLLISION
```

</p>
</details>


#### Stability
Every time I logged into the machine, the CPU was somewhere between 50% and 100%, memory was between 55% and 65%.
In total, puppeteer crashed 34 times (roughly one crash every 13k pages). The library was always able to recover.

**Comment by bangbambang** [comment]
How did you get those stats, especially crawling errors? Would love to provide some stats from my run.

I've been using this library in production for about 2 months to grab screenshots. So far, for page rendering I'm able to maximize cpu efficiency by setting workers to 2*cpu core (used to use 3*core, reduced for rate-limiting purpose). Managed to process ~60000 pages daily.

The worker was quite resilient and never crashed AFAIK, only got stopped during deployment process. The only thing that still troubling me was intermittent TimeoutError during peak traffic (nothing to do with puppeteer).

**Comment by nettad** [comment]
@bangbambang - do you close the cluster after every batch or do you keep it running and only close if the server shuts down?

**Comment by thomasdondorf** [comment]
@bangbambang I got the crawling error statistics with a error handler and a shell one-liner:

My task error handler looked like this:

    cluster.on('taskerror', (err, url) => {
      console.error((new Date()).toJSON() + `  Error crawling ${url}: ${err.message}`);
    });

I wrote the stderr into a log file (`2> LOG_FILE.txt`). After the run I used the following shell one-liner to produce the numbers (basically extracts the error message, counts them and sorts them):

    cat LOG_FILE.txt | grep "  Error crawling" | sed 's/.*Error crawling http:\/\/[^ ]*: //g' | sed 's/ at .*//g' | sort | uniq -c | sort -nr

**Comment by bangbambang** [comment]
@nettad workers keep running unless there are new version pushed or in the event of network error (the process is gracefully killed. But since it's auto-restarted every half a minute, the log was quite ugly during network downtime).

The config itself is quite simple (I take a few tips from [this browserless post](https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html)).  Few notable tweaks:

- use either `CONCURRENCY_CONTEXT` or `CONCURRENCY_BROWSER` and set puppeteer's `userDataDir` to ramdisk.
- Since loading extension is infeasible, I use [request interceptor](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) extensively on a known problematic resource (see one of the list from [filterlists](https://filterlists.com/) for reference).
- Enforce a reasonable timeout rather than tweaking timeout to account for network congestion. As far as experience goes, network error was usually the one causing chrome to crash.

```
const cluster = await Cluster.launch({
    puppeteerOptions: {
      headless: true,
      ignoreHTTPSErrors: env.IGNORE_HTTPS || false,
      args: ['--disable-http2'],
      timeout: env.PUPPETEER_TIMEOUT || 30000,
    },
    concurrency: Cluster.CONCURRENCY_CONTEXT,
    maxConcurrency: parseInt(env.MAX_WORKER) || 4,
    skipDuplicateUrls: false,
    monitor: env.MONITOR === 'true' || false,
    timeout: env.PUPPETEER_TIMEOUT*2 || 60000,
  });

```

**Comment by thomasdondorf** [comment]
Closing this for now. Might reopen in the future when I'm panning on adding more runs.
