### ISSUE TITLE
'--no-startup-window' not working

### ISSUE THREAD

**Issue by quetzalsly** [thomasdondorf/puppeteer-cluster#252]
`'--no-startup-window'` causes `puppeteer-cluster` to not be able to run at all. I don't want the `about:blank` pages, I need to only create new pages for `puppeteer-extra` stealth functionality to work.

**Comment by thomasdondorf** [comment]
I don't know what `--no-startup-window` does and I don't understand the problem. Feel free to add more details and reopen the issue.
