### ISSUE TITLE
PDF loss

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [thomasdondorf/puppeteer-cluster#264]
To the cluster I add for example 1000 url to files. When the cluster ends, it has generated me only 850 or so.
If I set it with maxConcurrency to 1 it does generate 1000 pdfs.

`await cluster.task(async ({page, data: url}) => {
            var contentHtml = await fs.readFileSync(url, 'utf8');
            await page.setContent(contentHtml);
            await page.pdf({
                path: "./generated-pdfs/" + Date.now() + "_g.pdf",
                format: "A4",
                margin: {top: '2mm', right: '2mm', bottom: '2mm', left: '2mm'},
                printBackground: true
            });
            fs.unlinkSync(url);
        });`
I have this code inside cluster.

**Comment by Sinon02** [comment]
I met the similar problems when trid to render 1000 images and save them by page.screenshot(). If maxConcurrency is not 1, some images will not be saved. 
So can someone tell me what causes this problem and how to prevent this?
