### ISSUE TITLE
Browser does not connect to browserWSEndpoint

### ISSUE THREAD

**Issue by gsidsid** [thomasdondorf/puppeteer-cluster#268]
I'm using a pool of chromium instances on a high-bandwidth server for my browserWSEndpoint (browserWSEndpoint: 'ws://server:XXXX'). 

When I run a task on the puppeteer pool, my server does not receive any new connections, leading me to believe the browserWSEndpoint launch option is not passed through. Is this the case? Do any workarounds exist?

**Comment by thomasdondorf** [comment]
This is currently not supported. See #220

**Comment by gvojtko** [comment]
Still no solution?
