### ISSUE TITLE
Can you share an example ...

### ISSUE THREAD

**Issue by twg-group** [thomasdondorf/puppeteer-cluster#274]
Hello! Can you share `Progress view and monitoring statistics` example? (Like at README)

![Progress view and monitoring statistics](https://camo.githubusercontent.com/2f1f017ac8aca4669de5788aef7b53178ed086db/68747470733a2f2f692e696d6775722e636f6d2f6b6f474e6b424e2e676966)

**Comment by arekom** [comment]
Hey, to display stats while running the cluster pass the `monitor: true` into Cluster launch options,  you can find more details in here: [Cluster options](https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions)

**Comment by twg-group** [comment]
I have to be more observant, thanks!
