### ISSUE TITLE
How use proxy?

### ISSUE THREAD

**Issue by webmarts2019** [thomasdondorf/puppeteer-cluster#278]
Hi
How can we use proxy with this library?
If any one share an example it will be very helpful.
Thanks

**Comment by drmanhatin** [comment]
let cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_CONTEXT,
    maxConcurrency: 2,
    puppeteerOptions: { headless: false , 
     args: [ '--proxy-server=INSERT PROXY IP HERE' ]
    }
  });

**Comment by thomasdondorf** [comment]
Thanks @drmanhatin

**Comment by iostate** [comment]
@thomasdondorf What if you need to authenticate a proxy? It seems that when I use page.authenticate within a cluster.task, it does not authenticate.
