### ISSUE TITLE
Can you add an idle event

### ISSUE THREAD

**Issue by kanxue660** [thomasdondorf/puppeteer-cluster#29]
There is a requirement, a database table, there is a lot of url, need to be accessed one by one, I want to read in batches to prevent too much memory, the program has been running, only every once in a while to read the database, and then execute, Can you add an idle event to this loop? Read the database only when you are idle, I wonder if this method is feasible

**Comment by thomasdondorf** [comment]
Do you really need an event or can you use [Cluster.idle()](https://github.com/thomasdondorf/puppeteer-cluster#clusteridle)?

Example using `Cluster.idle`:

```
while (...) {
  // Read URLs from database
  const urlsFromDatabase = await getURLsFromDatabase();
  
  // call cluster.queue for each URL
  for ... { cluster.queue(...); }
  
  // wait for idle, then start again
  await cluster.idle();
}
```

**Comment by kanxue660** [comment]
Oh, I'll try.Thank you

**Comment by kanxue660** [comment]
The problem has been solved and this approach is feasible
