### ISSUE TITLE
Program hang when maxConcurrency is set over 50

### ISSUE THREAD

**Issue by datasunny** [thomasdondorf/puppeteer-cluster#3]
First of all, great project!
I tried the example while set maxConcurrency = 50/100. What I noticed is when set to 100, pretty much every time the program will hang somewhere. When set to 50, program will hang sometimes. Not sure what caused this issue. Thanks for any input.

**Comment by thomasdondorf** [comment]
Thanks you! Can you give some more information about your application? Are you hitting any limits on memory, CPU or throughput? These are the limiting factors.

You can use nload and htop (for linux). nload shows you the network usage and htop shows you the usage of memory and CPU. Start your application and monitor the usage of the resources to check for the limit.

It would be nice if you could report back if the problem is related to limited resources or to the library.

**Comment by datasunny** [comment]
Here is my program, almost identical to the example:
-------------------------------------------------------------------------------------------------
const { Cluster } = require('puppeteer-cluster');
const fs = require('fs');

(async () => {
    const cluster = await Cluster.launch({
        concurrency: Cluster.CONCURRENCY_CONTEXT,
        maxConcurrency: 50,
        monitor: true,
    });

    // Extracts document.title of the crawled pages
    await cluster.task(async ({ page, data: url }) => {
        await page.goto(url, { waitUntil: 'domcontentloaded' });
        const pageTitle = await page.evaluate(() => document.title);
        console.log(`Page title of ${url} is ${pageTitle}`);
    });

    // In case of problems, log them
    cluster.on('taskerror', (err, data) => {
        console.log(`  Error crawling ${data}: ${err.message}`);
    });

    var urls = fs.readFileSync('urls.txt').toString().split("\n");
    urls.splice(urls.length-1);
    for (let i = 0; i < urls.length; i++) {
      await cluster.queue(urls[i]);
    };

    await cluster.idle();
    await cluster.close();
})();
-----------------------------------------------------------------------------------------------

'urls.txt' is a file with few hundred URLs in it, 1 URL per line.
What I noticed is when the program hangs, the CPU usage drops from 95-99% to 5-10% and memory usage is about 70-75%. The network usage drops to almost nothing.

**Comment by thomasdondorf** [comment]
So, are you hitting limits on CPU, memory and throughput? Maybe could you tell me what kind of machine you have? What CPU, how much memory?

I'm thinking of two things that could help you (assuming you are not hitting any limits):

* Change `Cluster.CONCURRENCY_CONTEXT` to `Cluster.CONCURRENCY_BROWSER`. This will result in 50 independent browsers instead of 50 independent contexts.
* Set `workerCreationDelay` to something like `200` to prevent a network/CPU peak right at the start. This will create an additional worker every 0.2s instead of creating 50 directly.

**Comment by datasunny** [comment]
CPU: i5-2400 (4 core)
Memeory: 16GB
I tried changing 'Cluster.CONCURRENCY_CONTEXT' to 'Cluster.CONCURRENCY_BROWSER', and the average load shot from <10 to 100+ as create/shutdown independent browser used a lot more resource than create/reuse browser pages. What I found is when set to 'Cluster.CONCURRENCY_BROWSER', program won't hang.

**Comment by thomasdondorf** [comment]
Just to give you an idea: I also have a machine with an i5 with 4 cores. I can open roughly 10 contexts or browsers before the CPU reaches 100%.

A machine with 4 cores will not be able to handle 100 browser windows or instances. But I will investigate why the example with the option CONTEXT gets stuck in such a case. Maybe the library should show a warning.

**Comment by datasunny** [comment]
I switch to a powerful server with E5-2640 v4 X 4 CPU (40 cores in total) and 64 GB memory. With the same setting 'Cluster.CONCURRENCY_CONTEXT' and 50 'maxConcurrency', the program still hangs. It happens once during the 3 runs I tested.

**Comment by thomasdondorf** [comment]
So far I was not able to reproduce the problem. Can you maybe run your application with [debugging ](https://github.com/thomasdondorf/puppeteer-cluster#debugging) enabled and share the log file with me?

`DEBUG='puppeteer-cluster:*' node examples/minimal > log.txt`

**Comment by datasunny** [comment]
Debug log i got when program hangs:
----------------------------------------------------------------------------  
  puppeteer-cluster:Cluster Launching +0ms
  puppeteer-cluster:Worker Starting #0 +0ms
  puppeteer-cluster:Worker Starting #1 +2ms
  puppeteer-cluster:Worker Starting #2 +0ms
  puppeteer-cluster:Worker Starting #3 +1ms
  puppeteer-cluster:Worker Starting #4 +0ms
  puppeteer-cluster:Worker Starting #5 +0ms
  puppeteer-cluster:Worker Starting #6 +0ms
  puppeteer-cluster:Worker Starting #7 +1ms
  puppeteer-cluster:Worker Starting #8 +0ms
  puppeteer-cluster:Worker Starting #9 +0ms
  puppeteer-cluster:Worker Starting #10 +0ms
  puppeteer-cluster:Worker Starting #11 +0ms
  puppeteer-cluster:Worker Starting #12 +7ms
  puppeteer-cluster:Worker Starting #13 +0ms
  puppeteer-cluster:Worker Starting #14 +0ms
  puppeteer-cluster:Worker Starting #15 +0ms
  puppeteer-cluster:Worker Starting #16 +1ms
  puppeteer-cluster:Worker Starting #17 +0ms
  puppeteer-cluster:Worker Starting #18 +0ms
  puppeteer-cluster:Worker Starting #19 +0ms
  puppeteer-cluster:Worker Starting #20 +0ms
  puppeteer-cluster:Worker Starting #21 +7ms
  puppeteer-cluster:Worker Starting #22 +0ms
  puppeteer-cluster:Worker Starting #23 +1ms
  puppeteer-cluster:Worker Starting #24 +0ms
  puppeteer-cluster:Worker Starting #25 +0ms
  puppeteer-cluster:Worker Starting #26 +1ms
  puppeteer-cluster:Worker Starting #27 +0ms
  puppeteer-cluster:Worker Starting #28 +4ms
  puppeteer-cluster:Worker Starting #29 +7ms
  puppeteer-cluster:Worker Starting #30 +1ms
  puppeteer-cluster:Worker Starting #31 +0ms
  puppeteer-cluster:Worker Starting #32 +0ms
  puppeteer-cluster:Worker Starting #33 +0ms
  puppeteer-cluster:Worker Starting #34 +1ms
  puppeteer-cluster:Worker Starting #35 +0ms
  puppeteer-cluster:Worker Starting #36 +0ms
  puppeteer-cluster:Worker Starting #37 +1ms
  puppeteer-cluster:Worker Starting #38 +0ms
  puppeteer-cluster:Worker Starting #39 +0ms
  puppeteer-cluster:Worker Starting #40 +0ms
  puppeteer-cluster:Worker Starting #41 +0ms
  puppeteer-cluster:Worker Starting #42 +1ms
  puppeteer-cluster:Worker Starting #43 +0ms
  puppeteer-cluster:Worker Starting #44 +0ms
  puppeteer-cluster:Worker Starting #45 +1ms
  puppeteer-cluster:Worker Starting #46 +0ms
  puppeteer-cluster:Worker Starting #47 +0ms
  puppeteer-cluster:Worker Starting #48 +0ms
  puppeteer-cluster:Worker Starting #49 +1ms
  puppeteer-cluster:log Error crawling 'http://ntq-partnership.com' // message: net::ERR_NAME_NOT_RESOLVED at http://ntq-partnership.com +0ms
  puppeteer-cluster:log Error crawling 'http://estila.es' // message: net::ERR_NAME_NOT_RESOLVED at http://estila.es +181ms
  puppeteer-cluster:log Error crawling 'http://resume.se' // message: net::ERR_CERT_SYMANTEC_LEGACY at http://resume.se +472ms
  puppeteer-cluster:log Error crawling 'http://sparkasse-freiburg.de' // message: net::ERR_CERT_SYMANTEC_LEGACY at http://sparkasse-freiburg.de +3s
  puppeteer-cluster:Worker Error getting browser page (try: 0), message: Timeout hit: 5000 +10s
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error getting browser page (try: 0), message: Timeout hit: 5000 +913ms
  puppeteer-cluster:BrowserContext Repair requested +913ms
  puppeteer-cluster:Worker Error getting browser page (try: 0), message: Timeout hit: 5000 +61ms
  puppeteer-cluster:BrowserContext Repair requested +61ms
  puppeteer-cluster:Worker Error getting browser page (try: 0), message: Timeout hit: 5000 +403ms
  puppeteer-cluster:BrowserContext Repair requested +403ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://novopay.in': Timeout hit: 5000 +5s
  puppeteer-cluster:BrowserContext Repair requested +5s
  puppeteer-cluster:Worker Error closing browser instance for 'http://movies123.top': Timeout hit: 5000 +596ms
  puppeteer-cluster:BrowserContext Repair requested +596ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://dget.nic.in': Timeout hit: 5000 +213ms
  puppeteer-cluster:BrowserContext Repair requested +213ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://arabo.com': Timeout hit: 5000 +993ms
  puppeteer-cluster:BrowserContext Repair requested +993ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://unbelievable-facts.com': Timeout hit: 5000 +1s
  puppeteer-cluster:BrowserContext Repair requested +1s
  puppeteer-cluster:Worker Error closing browser instance for 'http://viennaairport.com': Timeout hit: 5000 +7s
  puppeteer-cluster:BrowserContext Repair requested +7s
  puppeteer-cluster:Worker Error closing browser instance for 'http://ukuleleunderground.com': Timeout hit: 5000 +1s
  puppeteer-cluster:BrowserContext Repair requested +1s
  puppeteer-cluster:Worker Error closing browser instance for 'http://visit-x.net': Timeout hit: 5000 +540ms
  puppeteer-cluster:BrowserContext Repair requested +540ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://routesonline.com': Timeout hit: 5000 +1s
  puppeteer-cluster:BrowserContext Repair requested +1s
  puppeteer-cluster:Worker Error closing browser instance for 'http://scriptcase.net': Timeout hit: 5000 +1s
  puppeteer-cluster:BrowserContext Repair requested +1s
  puppeteer-cluster:Worker Error closing browser instance for 'http://fruugo.com': Timeout hit: 5000 +168ms
  puppeteer-cluster:BrowserContext Repair requested +170ms
  puppeteer-cluster:log Error crawling 'http://usra.edu' // message: Timeout hit: 30000 +27s
  puppeteer-cluster:log Error crawling 'http://beztabu.net' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://pokerprolabs.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://lacroixwater.com' // message: Timeout hit: 30000 +5ms
  puppeteer-cluster:log Error crawling 'http://ypaithros.gr' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://edmontonsun.com' // message: Timeout hit: 30000 +4ms
  puppeteer-cluster:log Error crawling 'http://lk21.blue' // message: Timeout hit: 30000 +4ms
  puppeteer-cluster:log Error crawling 'http://graphicpanda.net' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://joinmyband.co.uk' // message: Timeout hit: 30000 +4ms
  puppeteer-cluster:log Error crawling 'http://fontyukle.net' // message: Timeout hit: 30000 +1ms
  puppeteer-cluster:log Error crawling 'http://nissan-rentacar.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://lemet.fr' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://theybf.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://modsy.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://boyslife.org' // message: Timeout hit: 30000 +7ms
  puppeteer-cluster:log Error crawling 'http://ventadepisos.com' // message: Timeout hit: 30000 +5ms
  puppeteer-cluster:log Error crawling 'http://invictory.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://bulkapothecary.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://notch.one' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://mytaxi.com' // message: Timeout hit: 30000 +1ms
  puppeteer-cluster:log Error crawling 'http://theflowerseason.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://articlekz.com' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://delcampe.it' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://minecraftonly.ru' // message: Timeout hit: 30000 +0ms
  puppeteer-cluster:log Error crawling 'http://pepperjam.sharepoint.com' // message: Timeout hit: 30000 +469ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://uacinemas.com.hk': Timeout hit: 5000 +1s
  puppeteer-cluster:BrowserContext Repair requested +1s
  puppeteer-cluster:log Error crawling 'http://wavy.com' // message: Timeout hit: 30000 +817ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://slarticle.com': Timeout hit: 5000 +2s
  puppeteer-cluster:BrowserContext Repair requested +2s
  puppeteer-cluster:Worker Error closing browser instance for 'http://qamshy.kz': Timeout hit: 5000 +524ms
  puppeteer-cluster:BrowserContext Repair requested +524ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://megustaleer.com': Timeout hit: 5000 +168ms
  puppeteer-cluster:BrowserContext Repair requested +169ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://ifce.fr': Timeout hit: 5000 +790ms
  puppeteer-cluster:BrowserContext Repair requested +789ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://phoenixpubliclibrary.org': Timeout hit: 5000 +802ms
  puppeteer-cluster:BrowserContext Repair requested +802ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://usra.edu': Timeout hit: 5000 +182ms
  puppeteer-cluster:BrowserContext Repair requested +182ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://beztabu.net': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://pokerprolabs.com': Timeout hit: 5000 +1ms
  puppeteer-cluster:BrowserContext Repair requested +1ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://lacroixwater.com': Timeout hit: 5000 +5ms
  puppeteer-cluster:BrowserContext Repair requested +5ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://ypaithros.gr': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +1ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://edmontonsun.com': Timeout hit: 5000 +3ms
  puppeteer-cluster:BrowserContext Repair requested +2ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://lk21.blue': Timeout hit: 5000 +4ms
  puppeteer-cluster:BrowserContext Repair requested +4ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://graphicpanda.net': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://joinmyband.co.uk': Timeout hit: 5000 +6ms
  puppeteer-cluster:BrowserContext Repair requested +6ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://fontyukle.net': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://nissan-rentacar.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://lemet.fr': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://theybf.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://modsy.com': Timeout hit: 5000 +8ms
  puppeteer-cluster:BrowserContext Repair requested +8ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://boyslife.org': Timeout hit: 5000 +3ms
  puppeteer-cluster:BrowserContext Repair requested +4ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://ventadepisos.com': Timeout hit: 5000 +1ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://invictory.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://bulkapothecary.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://notch.one': Timeout hit: 5000 +1ms
  puppeteer-cluster:BrowserContext Repair requested +1ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://mytaxi.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://theflowerseason.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://articlekz.com': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://delcampe.it': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://minecraftonly.ru': Timeout hit: 5000 +0ms
  puppeteer-cluster:BrowserContext Repair requested +0ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://pepperjam.sharepoint.com': Timeout hit: 5000 +469ms
  puppeteer-cluster:BrowserContext Repair requested +469ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://wavy.com': Timeout hit: 5000 +817ms
  puppeteer-cluster:BrowserContext Repair requested +817ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://troc.com': Timeout hit: 5000 +532ms
  puppeteer-cluster:BrowserContext Repair requested +532ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://epson.co.id': Timeout hit: 5000 +395ms
  puppeteer-cluster:BrowserContext Repair requested +395ms
  puppeteer-cluster:Worker Error closing browser instance for 'http://kalender-365.nl': Timeout hit: 5000 +889ms
  puppeteer-cluster:BrowserContext Repair requested +889ms

**Comment by thomasdondorf** [comment]
Thank you for taking the time and reporting the bug. After multiple attempts I finally figured out what the problem was. I'm sorry it took that long.

For anyone interested: In case your system was under heavy load, my script would assume the context/browser starting would fail although it might just have taken longer than the timeout (5 seconds). In that case, the opened window would be counted (correctly) as open would not be used and therefore prevent a repairing in case of errors.

The problem should be solved now. New release is coming soon.

**Comment by ritik-peoplelink** [comment]
is there any way to wait on browser or page till time which we want because after completion the job worker goes automatically in idle mode.

**Comment by noname29** [comment]
@thomasdondorf hi what is the solution now, I get the same behavior. Can we have context launch timeout option instead and set it ourselvels ?
