### ISSUE TITLE
importing / requiring Cluster

### ISSUE THREAD

**Issue by MaxTwentythree** [thomasdondorf/puppeteer-cluster#30]
Hi,

thanks for this awesome library :)

Unfortunately, I do not seem to get it to work, as none of the importing / requiring mechanisms seem to work:

const { Cluster } = require('puppeteer-cluster'); -> Cluster = undefined
import { Cluster } from 'puppeteer-cluster'; -> Cluster = undefined
import Cluster from 'puppeteer-cluster'; -> Cluster = {}

I'm on Node v8.11.4

What am I doing wrong?

**Comment by MaxTwentythree** [comment]
Yeah, node and npm is setup correctly..
It could be meteor.js which caused the problem..
However, sometimes it just needs a new day to fix a problem.
I just tried it on another machine and lo and behold, it works with 
`import { Cluster } from 'puppeteer-cluster';` :)
Still wondering what went wrong on the other machine.
If I find out sth I'll post it here, but for now the issue can be closed.
Thank you for your quick response!

**Comment by thomasdondorf** [comment]
Thanks for confirming it was not related to the library.

Feel free to reopen or comment if you found out what the problem was.

**Comment by bernhard-adobe** [comment]
hi there, I noticed a similar issue and this might be coming from ESM modules.
I have them activated via `"type:" "module"` in my `package.json`

destructuring worked for me:
```JavaScript
import  ClusterModule  from 'puppeteer-cluster';
const { Cluster } = ClusterModule;

```
source: https://stackoverflow.com/questions/47277887/node-experimental-modules-requested-module-does-not-provide-an-export-named
