### ISSUE TITLE
Warning puppeteer-cluster@0.21.0" has incorrect peer dependency "puppeteer@^1.5.0 || ^2.0.0 || ^3.0.0".

### ISSUE THREAD

**Issue by crossinghoods** [thomasdondorf/puppeteer-cluster#312]
Have installed **puppeteer 5.2.0** (Latest as of 18th July 2020)
but when I do **yarn install puppeteer-cluster** I am getting the following warning

### Linking dependencies...
**warning** " > puppeteer-cluster@0.21.0" has incorrect peer dependency "puppeteer@^1.5.0 || ^2.0.0 || ^3.0.0".

**Comment by thomasdondorf** [comment]
Fixed by latest version.
