### ISSUE TITLE
[QUESTION] Should page be closed when using long lasting cluster

### ISSUE THREAD

**Issue by bausano** [thomasdondorf/puppeteer-cluster#367]
I have a cluster for which I have defined a task. As per example in the `README.md`, I have a closure which accepts a page instance as an argument. I navigate to a page and capture screenshot. I don't do anything else to the page. In the example, there's an `await` for idle and then the cluster is closed. Should I change the behaviour of my closure if the cluster is never closed?

I suspect I have got a memory leak somewhere in my service and one of the causes I am investigating is whether the cluster closes pages after I am done using them. I use `concurrency: Cluster.CONCURRENCY_CONTEXT` option.

```typescript
await puppeteer.task(async ({ page }) => {
  // ... my screenshot logic

  // do I need to do this?
  await page.close();
});
```

**Comment by bausano** [comment]
Will ask this question on SO instead as per https://github.com/thomasdondorf/puppeteer-cluster/issues/150.

**Comment by MinSomai** [comment]
not necessary to close page, it is done by the lib.

https://github.com/thomasdondorf/puppeteer-cluster/issues/34#issuecomment-427630925
