### ISSUE TITLE
Usage in an HTTP environment.

### ISSUE THREAD

**Issue by j** [thomasdondorf/puppeteer-cluster#38]
Can I use this in `micro` / `express` / etc and be able to have an endpoint process a "screenshot" task and return a value when the task completes?

Is this a thing?

**Comment by thomasdondorf** [comment]
Sure, currently there is no callback or "execute" function that waits for execution, but you can ether provide a callback function or give the response object to the task function.

#### First option:
The cluster and server are separated nicely. In the future the library will support this scenario more easily by offering an `execute` function which will block until the queued task is executed.
```js
// Task function receives url and callback
await cluster.task(async ({ page, data: { url, cb }) => {
    await page.goto(url);
    const screen = await page.screenshot();
    // ...
    cb(screen);
});

// Server
... (req, res) => {
    cluster.queue({
        url: 'http://...',
        cb: (screen) => {
            res.end(screen); // or whatever you want to send back or do
        }
    });
}
```

#### Second option:
Less code but puppeteer and server code is mixed up now:
```js
// Task function receives url and res
await cluster.task(async ({ page, data: { url, res }) => {
    await page.goto(url);
    const screen = await page.screenshot();
    // ...
    res.end(screen);
});

// Server
... (req, res) => {
    cluster.queue({
        url: 'http://...',
        res
    });
}
```
