### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by yotamshapira** [thomasdondorf/puppeteer-cluster#382]
Hi,

While Puppeteer has been bumped to version 8, this (awesome!) project still supports Puppeteer v5.2.1 .
Is this still being maintained?

Thanks,
Yotam

**Comment by redareda9** [comment]
21 Days ago.
Seems like it's not maintained anymore. 
Any alternative?

**Comment by thomasdondorf** [comment]
Yes, this repository is currently not being actively maintained. I'm not using puppeteer myself anymore.

I can add a contributor, if someone wants to jump in. The release/testing process is basically automated. When a commit on the master is tagged, a new build is automatically released.

**Comment by danielmockaitis** [comment]
Is there another project that's being maintained you might recommend? Perhaps even something other than Puppeteer?

**Comment by thomasdondorf** [comment]
See #428
