### ISSUE TITLE
Upgrade to new version for current version of puppeteer-cluster

### ISSUE THREAD

**Issue by zydjohnHotmail** [thomasdondorf/puppeteer-cluster#389]
Hello:
C:\puppeteer-cluster>npm install puppeteer-cluster
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: puppeteer-cluster@1.0.0
npm ERR! Found: puppeteer@8.0.0
npm ERR! node_modules/puppeteer
npm ERR!   puppeteer@"^8.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer puppeteer@"^1.5.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0" from puppeteer-cluster@0.22.0
npm ERR! node_modules/puppeteer-cluster
npm ERR!   puppeteer-cluster@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\...\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\_logs\2021-04-01T07_42_47_438Z-debug.log

C:\puppeteer-cluster>npm list
puppeteer-cluster@1.0.0 C:\puppeteer-cluster
`-- puppeteer@8.0.0

C:\puppeteer-cluster>
I want to install puppeteer-cluster npm package and give it a try, unfortunately, the current version (0.22.0) can't be installed with current version of puppeteer, which is 8.0.0 released about one month ago.  But puppeteer-cluster version 0.22.0 was released about 8 months ago.
Do you have plan for a new release for the near future?  For the time being, I can use older version of puppeteer, but use the latest version should always be a decent requirement.
Thanks,

**Comment by Tuki-M** [comment]
+1

**Comment by JoelKallgren** [comment]
+1

**Comment by youenchene** [comment]
+1 on 9.0.0

**Comment by fahminlb33** [comment]
I'm also having the same problem, but I've tried using puppeteer@9.0.0 and latest puppeteer-cluster and it works. I guess it should not be a breaking change to change puppeteer version to newest version.

**Comment by nfantone** [comment]
Apart from `yarn `complaining about requested peer dependency version, I did not notice any major issues with `puppeteer` `9.1.1`. Would be nice to get this going, though.

**Comment by filipbekic01** [comment]
Needed :)

**Comment by andreathniah** [comment]
Any updates to this?

**Comment by jvican** [comment]
Would be nice to have an update on this one. There have been a lot of upstream changes in puppeteer (now on version 12) and it feels a bit hacky to use the latest puppeteer with puppeteer-cluster.

**Comment by adriaanvanrossum** [comment]
You could use `npm install puppeteer-cluster3` from https://github.com/jdanyow/puppeteer-cluster

**Comment by 4nkitpatel** [comment]
any updates on this puppeteer (now on version 13) ?? which version of puppeteer-cluster should I use ?

**Comment by thomasdondorf** [comment]
Update of dependencies was released. See #428 for more information.
