### ISSUE TITLE
Puppeteer Cluster Best Practices

### ISSUE THREAD

**Issue by j** [thomasdondorf/puppeteer-cluster#39]
It's a guessing game right now to figure out the correct options based on CPU / Memory.

It'd be nice to know the best options for puppeteer-cluster on various systems.

I'm trying to figure out the best deployment strategy for "real-time" processing.  Many small instances vs fewer large instances, etc.

Ref: https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html

**Comment by thomasdondorf** [comment]
Yes, that is a good point, that's why I opened #25.

I will add more runs in the future when the library and API are more stable. :)
