### ISSUE TITLE
how to prevent close after run test

### ISSUE THREAD

**Issue by eriksape** [thomasdondorf/puppeteer-cluster#4]
all windows after queue ends closes, i want the window active

**Comment by thomasdondorf** [comment]
Do you want the cluster to stay alive after your jobs finished? Then remove the `cluster.close()` call. Then you cluster stays active and waits for new data to be queued.

**Comment by eriksape** [comment]
https://www.youtube.com/watch?v=up1sxOG4DXo
is cause one test i want to check is about a video view but the windows closes immediately the queue ends

**Comment by thomasdondorf** [comment]
Sorry, but I'm not sure, what the question or problem is. Let me explain what happens in the video: You queue 3 jobs with 2 workers with CONCURRENCY_CONTEXT. That means for each job a context is created and closed after it is finished.

So what happens is:
* Browser instance is launched
* A context is created for your first job (1/wikipedia)
* A second context is created (in parallel) for your second job (2/google)
* The second job (2/google) finishes first, the context is closed
* Another context is created for you third job (3/google)
* The third job (3/google) finishes, still before the first job (1/wikipedia), the context is closed
* The first job (1/wikipedia) finishes, the context is closed

As you are not closing the cluster, the browser instance stays open.

Maybe can you say what you are expecting or what you are trying to accomplish?

**Comment by eriksape** [comment]
Ok, I understood now, I want to context stays opens i think some cases one makes closes until a event.

**Comment by thomasdondorf** [comment]
So you have an (external) event that you need to wait for? You can do it with a promise.

```js
await cluster.queue(async ({ page }) => {
    await page.goto('https://www.google.com/');
    // Wait until promise resolves
    await new Promise((resolve, reject) => {
        // wait for event (simulated with setTimeout)
        setTimeout(() => {
            // event happens, resolve promise
            resolve();
        }, 5000);
    });
});
```

Just keep in mind, that it's bad to use asynchronous functions (like I did with setTimeout) as errors thrown inside cannot be caught by the library.

**Comment by thomasdondorf** [comment]
The code just waits for 1 second but I guess it solved your code and I can close the issue?
