### ISSUE TITLE
Same URL Concurrency

### ISSUE THREAD

**Issue by j** [thomasdondorf/puppeteer-cluster#40]
This goes away from the traditional idea of "New browser per task" or "New page per task".  This one is more about keeping a cluster of pages open the entire time and periodically refreshing them.  

Why would I want to do to this you ask?...

Let's say I have a page that has d3 charts and I want to turn all the charts into images (my actual product isn't d3 charts).  If the charts update in real time and I want a screenshot every 5 minutes (assuming there are 100s of charts), opening a page / browser each time takes a while.  If I just kept the tab open and kept screenshotting, then I'd have the screenshots a lot sooner.

Now for my more techy way:  I'm exposing a function to the site I'm screenshotting, and that function retrieves arguments from puppeteer/chrome to render specific items on the page.

Sudo-Code
```typescript
// browser
if (typeof window.getRenderOpts === 'function') {
    window.getRenderOpts().then((opts) => updateChart(opts));
}

// puppeteer
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');

async function getPageAndLock(): Promise<Page> {
  // .. get's a page that's idle or waits till one becomes idle...
}

async function pageIsReady(): Promise<Page> {
  // ...
}



... (req, res) => {
    const page = await getPageAndLock();

    await page.evaluate(`render(`${JSON.stringify({/* ... */)`)`);

    const screenshot = await page.screenshot(/* ... */);

    pageIsReady(page);

    res.send(screenshot);
}
```

It's probably out of the scope of this library, but I'm not sure if anyone would be interested in this type of concurrency.

I did benchmarks of "New browser per task", "New page per task", "Same page per task", and keeping the page open and taking screenshots periodically is A LOT FASTER.  I can get these benchmarks back if you want me to.  This was when I was experimenting.

**Comment by thomasdondorf** [comment]
You can simply just not close the page by awaiting a Promise at the end of your task function like this:

```js
const cluster = await Cluster.launch({
    // ...
    timeout: // set this to a large value
});

await cluster.task(async ({ page, data: url }) => {
    // ...
    await new Promise(resolve => {
         // call resolve() when you want to close the page
    });
});
```

Additionally, you need to increase the [timeout](https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions) launch option.

**Comment by semoal** [comment]
> You can simply just not close the page by awaiting a Promise at the end of your task function like this:
> 
> ```js
> const cluster = await Cluster.launch({
>     // ...
>     timeout: // set this to a large value
> });
> 
> await cluster.task(async ({ page, data: url }) => {
>     // ...
>     await new Promise(resolve => {
>          // call resolve() when you want to close the page
>     });
> });
> ```
> 
> Additionally, you need to increase the [timeout](https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions) launch option.

Sorry for reopen Thomas but it's a possibly no answer question on stackoverflow.
Does is possible to apply the same logic, maintain the browser open and just use the same tab forever with cluster.execute?

```js
  public async fromHtml(fromHtml: string, landscape: boolean, pdfOptions?: PDFOptions): Promise<Buffer | null> {
    if (!this.cluster) return null;

    const buffer = await this.cluster.execute({
      html: fromHtml,
    }, async ({ page, data: { html } }) => {
      await page.setContent(html, { waitUntil: "load" });

      return page.pdf({
        format: "A4",
        printBackground: true,
        landscape,
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        },
        ...pdfOptions,
      });
    });

    return buffer;
  }
```

I have this function, but i don't know how to keep that promise open (when is not possible because i need to return something to that)
Probably is not possible right now, but could be a nice feature. Thanx in advance

**Comment by thomasdondorf** [comment]
I don't understand the difference between your question and the question before. You can keep the tab open by not resolving the Promise as I posted above. It works the same with `cluster.execute` if that is your question.
