### ISSUE TITLE
Use "puppeteer-core" instead of "puppeteer"

### ISSUE THREAD

**Issue by j** [thomasdondorf/puppeteer-cluster#41]
Is it possible to use "puppeteer-core" instead of "puppeteer" for the sake of not having to specify the environment variable to exclude a chrome download?  I have to manually remove the chrome package from my distribution.

**Comment by thomasdondorf** [comment]
Currently, that is not possible, but I will add it in one of the next versions.

**Comment by chay22** [comment]
I don't know if this is related, but could you also please put into consideration to also allow another "puppeteer" package such as https://github.com/berstend/puppeteer-extra ?

**Comment by thomasdondorf** [comment]
Thanks for the idea. I will most likely add an option to pass a custom object which will be used as "puppeteer" object. So this will work then.

**Comment by thomasdondorf** [comment]
This is implemented in version `0.12`. You can pass a custom object to be used like shown in [this example](https://github.com/thomasdondorf/puppeteer-cluster/blob/master/examples/different-puppeteer-library.js). Give it a try :)
