### ISSUE TITLE
Does it support puppeteer ^10.1.0 version?

### ISSUE THREAD

**Issue by kybetter** [thomasdondorf/puppeteer-cluster#411]
I looked package.json file and found puppeteer dependence is ^5 version.

**Comment by kumar-muthu** [comment]
It does. But type checking fails, since underlying types have been renamed.

```
 const cluster = await Cluster.launch({
            concurrency: Cluster.CONCURRENCY_PAGE,
            puppeteer,
            timeout: 60000,
            puppeteerOptions: {
                executablePath,
                headless: true,
                args: [
                    '--no-sandbox'
                ]
            },
        });
```

This results in  typescript error  => `'headless' does not exist in type 'LaunchOptions'`.  In newer puppeteer `LaunchOptions` has been modified.  Probably `puppeteer-cluster` should reference PuppeteerNodeLaunchOptions instead ?

**Comment by michaelcox** [comment]
Even though the typing fails, it does still pass these options as-is to puppeteer. So you can just `ts-ignore` these options and TypeScript is happy and puppeteer gets the values correctly.

```typescript
 const cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_PAGE,
    puppeteer,
    timeout: 60000,
    puppeteerOptions: {
        // @ts-ignore
        executablePath,
        headless: true,
        args: [
            '--no-sandbox'
        ]
    },
});
```

**Comment by phattranky** [comment]
Set the types as `puppeteer.PuppeteerNodeLaunchOptions` works for me on the version 13.x

```
const cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_PAGE,
    puppeteer,
    timeout: 60000,
    puppeteerOptions: {
        executablePath,
        headless: true,
        args: [
            '--no-sandbox'
        ]
    } as puppeteer.PuppeteerNodeLaunchOptions,
});
```

**Comment by thomasdondorf** [comment]
New version is on the way.
