### ISSUE TITLE
Error "Navigation failed because browser has disconnected!"

### ISSUE THREAD

**Issue by thomasdondorf** [thomasdondorf/puppeteer-cluster#42]
This [error](https://travis-ci.org/thomasdondorf/puppeteer-cluster/jobs/445794521#L509) is happening. ~~Puppeteer version 1.9 [seems to be the reason](https://github.com/Codeception/CodeceptJS/issues/1275).~~

Edit: I just wrote crappy code (forgot an `await`). Fix is on the way..

**Comment by thomasdondorf** [comment]
If you are here after searching for that error message. You likely [forgot an `await`](https://github.com/thomasdondorf/puppeteer-cluster/commit/b27ae3e51549acf9cb520b8c5714f9ce3ae42305#diff-e8bbcd831eed2c2667aea8e03c198383L483) somewhere in your code.

**Comment by alexmacarthur** [comment]
I've been tinkering with an implementation to scrape ~1500 pages in one job, but still getting this error. `await` is used everywhere it needs to be. Have there been other reasons you've heard of that would cause this issue?

**Comment by thomasdondorf** [comment]
Seems to be a resource problem: #179
