### ISSUE TITLE
puppeteer-v22.0.0 breaking changes

### ISSUE THREAD

**Issue by nmaswood** [thomasdondorf/puppeteer-cluster#535]
# Issue

[Puppeteer 22.0](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0) has a number of breaking changes that effect puppeteer-cluster

# Question

* Is this project active / supporting contributions to support a migration to 22?
* Does anyone have an intuitive sense of how difficult that migration would be?

P.S.

Great project, I love using it. Thanks so much

**Comment by nigelellis** [comment]
Looks like PR was submitted to patch -- see https://github.com/thomasdondorf/puppeteer-cluster/pull/536

**Comment by thomasdondorf** [comment]
That PR was just merged and a new version was published.
