### ISSUE TITLE
Add more events

### ISSUE THREAD

**Issue by KartoffelToby** [thomasdondorf/puppeteer-cluster#58]
Something like:

        cluster.on('monitor', (data) => {
            console.log(data);
        });

**Comment by thomasdondorf** [comment]
I will probably go in the direction of offering a way to [query the status](https://github.com/thomasdondorf/puppeteer-cluster/issues/8#issuecomment-421307994). Then you can set up a `setInterval` function and call `cluster.stats()` yourself.

Sounds good?

**Comment by KartoffelToby** [comment]
Yea, sounds sweet, but maybe an event would be more useful

**Comment by thomasdondorf** [comment]
And when would you want the 'monitor' event to be triggered?

**Comment by KartoffelToby** [comment]
Every time a queue is done?

**Comment by thomasdondorf** [comment]
I guess a 'queue' event would be better suited then. I could add more events for v1.0.

**Comment by thomasdondorf** [comment]
The ["queue" event](https://github.com/thomasdondorf/puppeteer-cluster#event-queue) is now fired when something is queued via `queue` or `execute`.

**Comment by kfrajtak** [comment]
Hi. Does the queue event payload contain all the information the monitor is displaying? My idea is to retrieve the monitor part information on the server and send it to client through socket.

**Comment by thomasdondorf** [comment]
No, there is only the queued data/function inside the event. There currently is no "statistics API".
