### ISSUE TITLE
Inter Process Communication

### ISSUE THREAD

**Issue by ahmedolaibrahim** [thomasdondorf/puppeteer-cluster#59]
Hello There.
I have multiple instances of puppeteer that scrapes data from some sites. after scraping, each instance uses process.send() to output the data so that it can be saved to a database. I would love to know if it's possible to listen to data/message sent by each instance so that they can be saved to the DB same way we have `cluster.on('taskerror')` event handler and how to implement it. Regards.

**Comment by thomasdondorf** [comment]
Hi! Not sure if I understand you correctly. For each job (or each browser?) you want to have a callback function called? Why can you not put the call into the task function?

**Comment by thomasdondorf** [comment]
Closing this for due to inactivity. Feel free to reopen.
