### ISSUE TITLE
Suggestion: add to awesome-puppeteer

### ISSUE THREAD

**Issue by transitive-bullshit** [thomasdondorf/puppeteer-cluster#7]
Cool project -- would you consider adding it to [awesome-puppeteer](https://github.com/transitive-bullshit/awesome-puppeteer)?

**Comment by thomasdondorf** [comment]
Was about to add it, but @di3goleite already did it. Thank you :)

**Comment by di3goleite** [comment]
Oh! I'm sorry. But I'm happy to help you guys in some way. 💪
