### ISSUE TITLE
Minor type checking improvement for cluster.queue method

### ISSUE THREAD

**Issue by cyxou** [thomasdondorf/puppeteer-cluster#70]
First of all, thank you for your work!
I have a minor suggestion on improving type checking fot the `cluster.queue()` method.
Now we have this:

```ts
public async queue(
        data: JobData | TaskFunction,
        taskFunction?: TaskFunction,
    ): Promise<void> {
...
}
```

As one can inspect, `JobData` is of type `any` and it is used both as a first argument to `cluster.queue()` method as well as the `data` property of the `TaskFunctionArguments` interface. This approach does not provide sufficient type checking when we call the `cluster.queue()` method with two arguments. I'd suggest to use generic types here like this:

```ts
type QueueFunction<T> = (arg: QueueFunctionArguments<T>) => Promise<void>;

interface QueueFunctionArguments<T> {
  page: puppeteer.Page;
  data: T;
  worker: {
    id: number;
  };
}

public async queue<T>(
    data: T | TaskFunction,
    taskFunction?: QueueFunction<T>,
): Promise<void> {
...
}
```

**Comment by thomasdondorf** [comment]
Looks good. As this might break implementations, I'll put this into the roadmap for v1 (#8).

**Comment by thomasdondorf** [comment]
This could actually be implemented without being a breaking change by using `any` as default for the generics.

**Comment by thomasdondorf** [comment]
I just implemented this. You can now specify the types for input/output via `Cluster<input, output>`. `output` is used when `execute` is called.
