### ISSUE TITLE
Unable to return a variable from a queued function

### ISSUE THREAD

**Issue by andreathniah** [thomasdondorf/puppeteer-cluster#78]
Hi,

I am having a little trouble figuring out a way to return a variable from a queued function. 

Given the sample `function-queuing-complex.js` example, I have tried using both `return` and  `resolve` in `extractTitle` since I read from the README that `cluster.queue` returns a Promise. Both resulted in `undefined` being returned. A `Promise.all` doesn't seem to work either. Is this a bug or am I doing something wrong?

```javascript
const extractTitle = async ({ page, data: url }) => {
	await page.goto(url);
	const pageTitle = await page.evaluate(() => document.title);
 
        // How do I return pageTitle to use outside this async function?
};
```
```javascript
const task1= await cluster.queue("https://reddit.com/", extractTitle);
const task2 = await cluster.queue("https://twitter.com/", extractTitle);
Promise.all([task1, task2]).then(result => console.log(result)); // returns undefined
```

**Comment by thomasdondorf** [comment]
This is a misunderstanding regarding the Promise of the `cluster.queue` function. The Promise of the queue function resolves as soon as the job is queued, not when the job is finished.

This will change in Version 1. `queue` will not return a Promise anymore and there will be another function called `execute` which queues the data and waits until the job is finished.

For more discussion see #10

**Comment by andreathniah** [comment]
@thomasdondorf thank you clearing up my misunderstanding. Apologies if it's a basic question, but I'm still not sure how one would go about returning `pageTitle`. Plain old, calling of pageTitle as a variable outside of the function didn't work.

**Comment by thomasdondorf** [comment]
All good :)

Right now you cannot return data from with the function, but instead you can collect it via an array in the outer scope like this:

```javascript
const pageTitles = [];
const extractTitle = async ({ page, data: url }) => {
	await page.goto(url);
	const pageTitle = await page.evaluate(() => document.title);
	pageTitles.push(pageTitle);
};

// queue your pages

await cluster.idle(); // wait for the jobs to be finished

// pageTitles should now be filled with your page titles
```

Alternatively you could also use callbacks to collect your data (or create promises and use their resolve as callback).

Does that clear things up?

**Comment by andreathniah** [comment]
@thomasdondorf yes this certainly helps to clear things up! Thank you for helping me out with this!
