### ISSUE TITLE
page.setrequestinterception in puppeteer cluster not working

### ISSUE THREAD

**Issue by saiprashanth24** [thomasdondorf/puppeteer-cluster#80]

**Comment by saiprashanth24** [comment]
i am running puppeteer cluster with 100 urls at a time .
i am unable to page.set requestinterception 
i know i should do it while adding the urls to queue ....
is there any method that i can do it globally for all the urls in the crawler queue ?

**Comment by thomasdondorf** [comment]
I'm not sure I understand you. Every page is created before and destroyed after each task. So you have to call any function for each page. You can simply do this in the task function.

**Comment by saiprashanth24** [comment]
i got it ..actually i made a mistake .thank you
