### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by cmoen** [thomasdondorf/puppeteer-cluster#81]
This software seems really interesting and useful.

Do you have any plans on changing your open source license from the GNU General Public License 3.0 to something else, such as Apache License 2.0, BSD or MIT?

I'm asking since many individuals and organisations cannot use GPL-licensed software.  Thanks.

**Comment by thomasdondorf** [comment]
Thanks for bringing it up. I'm not 100% sure yet, but I will probably change it to MIT in the next release.

**Comment by hastebrot** [comment]
Looking forward to adapt puppeteer-cluster to speedup my react/polymer screenshot testing tool.

**Comment by thomasdondorf** [comment]
@mhaseebkhan Are you okay with a license change to MIT? As you made a commit it would be nice if you could confirm.

**Comment by hastebrot** [comment]
Maybe we can just replace these few lines?

**Comment by jkusa** [comment]
👍

**Comment by michael-mclawhorn** [comment]
That would be super helpful.

**Comment by cythrawll** [comment]
👍

**Comment by mattgraham1995** [comment]
👍

**Comment by daniellevinson** [comment]
👍

**Comment by aklish** [comment]
Yes Please

**Comment by thomasdondorf** [comment]
Didn't expect so much feedback 😊

I'll make a new release at the weekend which will be MIT.

**Comment by thomasdondorf** [comment]
New version `0.16.0` has just been released under MIT license. Happy crawling ;)
