### ISSUE TITLE
multiple crawl does not crawl all my urls.

### ISSUE THREAD

**Issue by saiprashanth24** [thomasdondorf/puppeteer-cluster#82]
when i run puppeteer cluster with 100 urls,it only crawls 98 or 99 urls ..
here is my code 

`const { Cluster } = require('puppeteer-cluster');
var link=[];
var total=0;
var start=3;
const size= process.argv[2];
for(let i =0;i<size;i++)
{ link.push(process.argv[start++]);} 

(async () => {
  const cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_PAGE,
    maxConcurrency:50,
    timeout:400000,
    monitor:false
  });

  await cluster.task(async ({ page, data: url }) => {
    const response=await page.goto(url,{timeout:100000,waitUntil: 'networkidle2'});
	console.log(response.url());

 	 if(response.status()==404){
		console.log('program encountered error');		
		return;
	}
	total++;   (counts the number of urls)

	const hrefs = await page.evaluate(() => {
  			const anchors = document.querySelectorAll('a');
			 return [].map.call(anchors, a => a.href);
							});  

  });
  
for(let i =0;i<size;i++){await cluster.queue(link[i]); }

  await cluster.idle();
  await cluster.close();

console.log(total);
process.exit(0);
   })();`

**Comment by saiprashanth24** [comment]
i will give 100 urls as command line arguments ..
i have printed final count .
But i get only 98  or 99.

**Comment by thomasdondorf** [comment]
This is your [second](80) "low effort" question and you didn't even respond to the answer to your first question. Please format your code and be more precise with your question. Then I'll have a look.

**Comment by saiprashanth24** [comment]
i formateed the code ..i am giving 100 urls as input .i will extract the outlinks from those 100 urls by using document.queryselector .and i will increment the total by one after processing each url..Atlast i print the total.i only prints 99 or 98.i even checked it by printing the input urls after crawling and they also printed only 99 urls ..has anyone had this issue before ?

**Comment by thomasdondorf** [comment]
I had a look at your code (even though it is still not properly formatted). You have this before you increment the variable `total`:

        if (response.status() == 404) {
            console.log('program encountered error');
            return;
        }

Are you sure the return statement is not the problem here? I'm closing this question for now as I don't think your problem is related to this library. Feel free to reopen, but then you should format your code properly.
