### ISSUE TITLE
Cannot find module ../dist

### ISSUE THREAD

**Issue by LeMoussel** [thomasdondorf/puppeteer-cluster#83]
I'm trying to puppeteer-cluster with [minimal.js](https://github.com/thomasdondorf/puppeteer-cluster/blob/master/examples/minimal.js) example. I'm getting the following error:

- Windows 7
- node: v10.15.à
- npm: v6.4.1

> D:\Developpement\NodeJS\minimal>node minimal.js
> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module '../dist'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (D:\Developpement\NodeJS\minimal\minimal.js:1:83)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

With my configuration the directory `../dist` does not exist.
I have 

> 24/01/2019  15:10    <REP>          .
> 24/01/2019  15:10    <REP>          ..
> 24/01/2019  15:10    <REP>          minimal
> 24/01/2019  15:04    <REP>          node_modules

I replace `const { Cluster } = require('../dist');` by `const { Cluster } = require('puppeteer-cluster');` It's OK.

**Comment by VikramTiwari** [comment]
After installing dependencies run `npm run build` before running any tests. The code is in typescript and needs to be built before it can be used.

**Comment by LeMoussel** [comment]
OK. Thanks.
