### ISSUE TITLE
Is it possible to create task queue dynamically 

### ISSUE THREAD

**Issue by SharpieX** [thomasdondorf/puppeteer-cluster#85]
I want to create a node server for scrapping using puppeteer (pass search term in GET request to scrap google search results)

currently my server is not able process more then 5 parallel request after its goes out of memory

**Comment by thomasdondorf** [comment]
I don't understand your question. Closing this for now.

Feel free to reopen, but please provide some more numbers (how much is your memory?) and specify your questions.
