### ISSUE TITLE
A way to handle a popup?

### ISSUE THREAD

**Issue by goodhyun** [thomasdondorf/puppeteer-cluster#95]
At a loss at dealing with this scenario.

https://stackoverflow.com/questions/46669788/how-to-handle-popups-in-puppeteer 
https://github.com/GoogleChrome/puppeteer/issues/2968#issuecomment-408526574 

You might need to listen 'targetcreated' from `browser` context to track the popup and do some actions on it.

**Comment by thomasdondorf** [comment]
Currently, the `browser` object is not accessible. Therefore this is not possible right now.

**Comment by Aliyss** [comment]
Unless I'm doing something wrong:

Managed to get it to work:
```js
cluster.browser.browser.once('targetcreated', target => console.log(target))
```

Please correct if wrong.

**Comment by goodhyun** [comment]
@Aliyss Thanks for the solution, it seems working well. I finally solved that 3 years old missing puzzle!
