### ISSUE TITLE
Crawler on demand instead a queue

### ISSUE THREAD

**Issue by mtatarau90** [thomasdondorf/puppeteer-cluster#96]
Hi Guys,

I try to use express to wrap a little REST API above of puppeteer, but i see the only way to add a new url is use the cluster queue. My concern is that i do "parallel" requests i will receive the wrong answer, i mean the content of another url. 

My question is: Is possible to run synchronous tasks ? 

Thanks and sorry for may bad english.

**Comment by thomasdondorf** [comment]
I hope I'm able to add a "execute" function soon. Right now you could always pass a callback like documented in [this question](https://github.com/thomasdondorf/puppeteer-cluster/issues/38).

**Comment by thomasdondorf** [comment]
The `Cluster.execute` function was added with version 0.13.0. Check out this example to see how to use it in a server environment: https://github.com/thomasdondorf/puppeteer-cluster/blob/master/examples/express-screenshot.js
